use std::path::{Path, PathBuf};

use miette::{Context, IntoDiagnostic, Result, miette};

const CONFIG_FILE: &str = "fontmin.config.jsonc";
const CONFIG_SCHEMA_FILE: &str = "node_modules/fontmin-rs/configuration_schema.json";
const CONFIG_SCHEMA_PATH: &str = "./node_modules/fontmin-rs/configuration_schema.json";
const DEFAULT_CONFIG: &str = r#"{
  // Generated by fontmin-rs init.
  "input": ["fonts/*.ttf"],
  "outDir": "build",
  "subset": {
    "text": "Hello",
    "basicText": true
  },
  "outputs": [
    { "format": "woff2" },
    { "format": "woff" },
    { "format": "css" }
  ],
  "css": {
    "fontFamily": "MyFont",
    "fontPath": "./",
    "fontDisplay": "swap"
  },
  "cache": {
    "enabled": true
  }
}
"#;

pub async fn run() -> Result<i32> {
    let config_path = PathBuf::from(CONFIG_FILE);

    if config_path.exists() {
        return Err(miette!("{CONFIG_FILE} already exists"));
    }

    let config = if Path::new(CONFIG_SCHEMA_FILE).is_file() {
        DEFAULT_CONFIG.replacen(
            "  \"input\"",
            &format!("  \"$schema\": \"{CONFIG_SCHEMA_PATH}\",\n  \"input\""),
            1,
        )
    } else {
        DEFAULT_CONFIG.to_owned()
    };

    tokio::fs::write(&config_path, config)
        .await
        .into_diagnostic()
        .wrap_err_with(|| format!("failed to write {}", config_path.display()))?;

    println!("created {CONFIG_FILE}");

    Ok(0)
}
