packages:
  - docs
  - packages/*
  - napi/*
  - npm/*
  - wasm/*
  - tasks/*
  - examples/*

overrides:
  tar: 7.5.19

allowBuilds:
  '@napi-rs/cli': true
  ttf2woff2: false

minimumReleaseAgeExclude:
  - '@napi-rs/*'
  - '@emnapi/*'
  - fontmin-rs

catalog:
  '@napi-rs/cli': ^3.7.3
  '@types/node': ^26.1.1
  tsdown: ^0.22.12
  typescript: ^7.0.2
  vitest: ^4.1.10

minimumReleaseAge: 0
ignoreWorkspaceRootCheck: true
packageManagerStrict: false
shellEmulator: true
