import { execFileSync } from 'node:child_process'
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { tmpdir } from 'node:os'
import { resolve } from 'node:path'
import { expect, it } from 'vitest'
import { inspect } from '../src/index'
import {
  currentDir,
  fixture,
  bin,
  flagsFromUsage,
  fontCollection,
  hasCmapRecord,
  sfntTableVersion,
  variableTtfFixture,
} from './api-fixtures'

it('exposes the frozen public command surface through the package bin', () => {
  const contract = JSON.parse(
    readFileSync(
      resolve(currentDir, '../../../contracts/public-api.json'),
      'utf8',
    ),
  ) as {
    cli: {
      commands: Record<
        string,
        { flags: string[]; shortFlags: string[]; positionals: string[] }
      >
      globalFlags: string[]
    }
  }
  const help = execFileSync(process.execPath, [bin, '--help'], {
    encoding: 'utf8',
  })
  const commands = [
    ...help.matchAll(/^\s*fontmin-rs (?<command>[a-z]+)(?:\s|$)/gmu),
  ]
    .map(match => match.groups?.['command'])
    .filter(command => command !== undefined)

  expect([...new Set(commands)].toSorted()).toStrictEqual(
    Object.keys(contract.cli.commands).toSorted(),
  )

  for (const [command, surface] of Object.entries(contract.cli.commands)) {
    const commandUsage = help
      .split('\n')
      .filter(line => line.trimStart().startsWith(`fontmin-rs ${command}`))
      .join('\n')

    expect(flagsFromUsage(commandUsage)).toStrictEqual(
      [...surface.flags, ...surface.shortFlags].toSorted(),
    )
    for (const positional of surface.positionals) {
      expect(commandUsage.toUpperCase()).toContain(`<${positional}`)
    }
  }

  for (const flag of contract.cli.globalFlags) {
    expect(() => execFileSync(process.execPath, [bin, flag])).not.toThrow()
  }
})

it('initializes a JSONC config through the package bin', () => {
  const workDir = mkdtempSync(resolve(tmpdir(), 'fontmin-rs-bin-init-'))
  const configPath = resolve(workDir, 'fontmin.config.jsonc')

  try {
    const packageDir = resolve(workDir, 'node_modules/fontmin-rs')

    mkdirSync(packageDir, { recursive: true })
    writeFileSync(resolve(packageDir, 'configuration_schema.json'), '{}')

    const stdout = execFileSync(process.execPath, [bin, 'init'], {
      cwd: workDir,
      encoding: 'utf8',
    })
    const config = readFileSync(configPath, 'utf8')

    expect(stdout).toContain('fontmin.config.jsonc')
    expect(config).toContain('Generated by fontmin-rs init')
    expect(config).toContain(
      '"$schema": "./node_modules/fontmin-rs/configuration_schema.json"',
    )
    expect(config).toContain('"input"')
    expect(config).toContain('"outputs"')
    expect(config).toContain('"woff2"')
    expect(config).toContain('"fontDisplay": "swap"')
    expect(config).toContain('"cache"')

    mkdirSync(resolve(workDir, 'fonts'))
    writeFileSync(
      resolve(workDir, 'fonts/roboto-regular.ttf'),
      readFileSync(fixture),
    )
    execFileSync(process.execPath, [bin, 'build', '--config', configPath], {
      cwd: workDir,
    })

    const woff2 = readFileSync(resolve(workDir, 'build/roboto-regular.woff2'))
    const woff = readFileSync(resolve(workDir, 'build/roboto-regular.woff'))

    expect(woff2.subarray(0, 4).toString('ascii')).toBe('wOF2')
    expect(woff.subarray(0, 4).toString('ascii')).toBe('wOFF')
    expect(
      readFileSync(resolve(workDir, 'build/roboto-regular.css'), 'utf8'),
    ).toContain("font-family: 'MyFont';")
  } finally {
    rmSync(workDir, { recursive: true, force: true })
  }
})

it('omits a dangling JSON Schema path when the package is not installed locally', () => {
  const workDir = mkdtempSync(resolve(tmpdir(), 'fontmin-rs-bin-init-schema-'))
  const configPath = resolve(workDir, 'fontmin.config.jsonc')

  try {
    execFileSync(process.execPath, [bin, 'init'], { cwd: workDir })

    expect(readFileSync(configPath, 'utf8')).not.toContain('"$schema"')
  } finally {
    rmSync(workDir, { recursive: true, force: true })
  }
})

it('refuses to overwrite an existing JSONC config through the package bin', () => {
  const workDir = mkdtempSync(
    resolve(tmpdir(), 'fontmin-rs-bin-init-existing-'),
  )
  const configPath = resolve(workDir, 'fontmin.config.jsonc')
  let stderr = ''

  writeFileSync(configPath, 'keep me')

  try {
    try {
      execFileSync(process.execPath, [bin, 'init'], { cwd: workDir })
    } catch (error) {
      stderr = String((error as { stderr?: Buffer }).stderr)
    }

    expect(stderr).toContain('already exists')
    expect(readFileSync(configPath, 'utf8')).toBe('keep me')
  } finally {
    rmSync(workDir, { recursive: true, force: true })
  }
})

it('subsets a TTF through the package bin', () => {
  const outputDir = mkdtempSync(resolve(tmpdir(), 'fontmin-rs-bin-subset-'))
  const output = resolve(outputDir, 'roboto-subset.ttf')

  try {
    execFileSync(process.execPath, [
      bin,
      'subset',
      fixture,
      '-o',
      output,
      '--text',
      'Hello',
    ])

    expect(readFileSync(output).byteLength).toBeLessThan(
      readFileSync(fixture).byteLength,
    )
  } finally {
    rmSync(outputDir, { recursive: true, force: true })
  }
})

it('selects collection faces across package bin font commands', () => {
  const workDir = mkdtempSync(resolve(tmpdir(), 'fontmin-rs-bin-collection-'))
  const source = readFileSync(fixture)
  const collectionPath = resolve(workDir, 'fonts.ttc')
  const variableCollectionPath = resolve(workDir, 'variable.ttc')
  const subsetPath = resolve(workDir, 'subset.ttf')
  const woffPath = resolve(workDir, 'font.woff')
  const instancePath = resolve(workDir, 'instance.ttf')

  try {
    writeFileSync(collectionPath, fontCollection([source, source]))
    writeFileSync(
      variableCollectionPath,
      fontCollection([readFileSync(variableTtfFixture)]),
    )

    const inventory = JSON.parse(
      execFileSync(
        process.execPath,
        [bin, 'inspect', collectionPath, '--json'],
        {
          encoding: 'utf8',
        },
      ),
    ) as { faces: unknown[]; format: string }
    expect(inventory.format).toBe('collection')
    expect(inventory.faces).toHaveLength(2)

    execFileSync(process.execPath, [
      bin,
      'subset',
      collectionPath,
      '--font-number',
      '1',
      '--text',
      'Hello',
      '--output',
      subsetPath,
    ])
    expect(inspect(readFileSync(subsetPath)).format).toBe('ttf')

    const coverage = JSON.parse(
      execFileSync(
        process.execPath,
        [
          bin,
          'coverage',
          collectionPath,
          '--font-number',
          '0',
          '--text',
          'A',
          '--json',
        ],
        { encoding: 'utf8' },
      ),
    ) as { supported: number[] }
    expect(coverage.supported).toStrictEqual([0x41])

    execFileSync(process.execPath, [
      bin,
      'convert',
      collectionPath,
      '--font-number',
      '0',
      '--format',
      'woff',
      '--output',
      woffPath,
    ])
    expect(readFileSync(woffPath).subarray(0, 4).toString('ascii')).toBe('wOFF')

    const bench = JSON.parse(
      execFileSync(
        process.execPath,
        [
          bin,
          'bench',
          collectionPath,
          '--font-number',
          '0',
          '--text',
          'A',
          '--json',
        ],
        { encoding: 'utf8' },
      ),
    ) as { operation: string }
    expect(bench.operation).toBe('subset')

    execFileSync(process.execPath, [
      bin,
      'instance',
      variableCollectionPath,
      '--font-number',
      '0',
      '--output',
      instancePath,
    ])
    expect(inspect(readFileSync(instancePath)).metadata.tables).not.toContain(
      'fvar',
    )
  } finally {
    rmSync(workDir, { recursive: true, force: true })
  }
})

it('subsets by glyph ID and writes a mapping report through the package bin', () => {
  const outputDir = mkdtempSync(
    resolve(tmpdir(), 'fontmin-rs-bin-subset-gids-'),
  )
  const output = resolve(outputDir, 'roboto-subset.ttf')
  const reportPath = resolve(outputDir, 'roboto-subset.json')

  try {
    execFileSync(process.execPath, [
      bin,
      'subset',
      fixture,
      '-o',
      output,
      '--text',
      'A',
      '--gids',
      '1,65535',
      '--glyph-names',
      'A,does.not.exist',
      '--layout-features',
      'liga',
      '--layout-scripts',
      'latn',
      '--layout-languages',
      'default',
      '--name-ids',
      '1',
      '--name-languages',
      '0x409',
      '--drop-tables',
      'GPOS',
      '--pass-through-tables',
      'gasp',
      '--retain-gids',
      '--retain-glyph-names',
      '--retain-legacy-cmap',
      '--retain-symbol-cmap',
      '--report',
      reportPath,
    ])

    const report = JSON.parse(readFileSync(reportPath, 'utf8')) as {
      glyphsRetained: number
      glyphNameToOldGid: { glyphName: string; oldGid: number }[]
      missingGids: number[]
      missingGlyphNames: string[]
      newToOld: (number | null)[]
      oldToNew: { newGid: number; oldGid: number }[]
      requestedGids: number[]
      requestedGlyphNames: string[]
      supportedGids: number[]
      supportedGlyphNames: string[]
    }

    expect(inspect(readFileSync(output)).metadata.glyphCount).toBe(39)
    expect(inspect(readFileSync(output)).metadata.tables).not.toContain('GPOS')
    expect(inspect(readFileSync(output)).metadata.tables).toContain('gasp')
    expect(sfntTableVersion(readFileSync(output), 'post')).toBe(0x0002_0000)
    expect(hasCmapRecord(readFileSync(output), 1, 0)).toBe(true)
    expect(report).toMatchObject({
      glyphsRetained: 39,
      missingGids: [65_535],
      missingGlyphNames: ['does.not.exist'],
      requestedGids: [1, 65_535],
      requestedGlyphNames: ['A', 'does.not.exist'],
      supportedGids: [1],
      supportedGlyphNames: ['A'],
    })
    expect(report.glyphNameToOldGid).toContainEqual({
      glyphName: 'A',
      oldGid: 38,
    })
    expect(report.oldToNew).toContainEqual({ newGid: 38, oldGid: 38 })
    expect(report.newToOld[2]).toBeNull()
  } finally {
    rmSync(outputDir, { recursive: true, force: true })
  }
})

it('reports character coverage through the package bin', () => {
  const stdout = execFileSync(
    process.execPath,
    [bin, 'coverage', fixture, '--text', 'A𠮷', '--json'],
    { encoding: 'utf8' },
  )
  const report = JSON.parse(stdout) as {
    coveragePercent: number
    missing: number[]
    requested: number[]
    supported: number[]
  }

  expect(report).toStrictEqual({
    coveragePercent: 50,
    missing: [134_071],
    requested: [0x41, 134_071],
    supported: [0x41],
  })
})

it('rejects missing glyphs in strict package bin subsets', () => {
  const outputDir = mkdtempSync(
    resolve(tmpdir(), 'fontmin-rs-bin-subset-strict-'),
  )
  const output = resolve(outputDir, 'roboto-subset.ttf')
  let stderr = ''

  try {
    try {
      execFileSync(process.execPath, [
        bin,
        'subset',
        fixture,
        '-o',
        output,
        '--text',
        'A𠮷',
        '--missing-glyphs',
        'error',
      ])
    } catch (error) {
      stderr = String((error as { stderr?: Buffer }).stderr)
    }

    expect(stderr).toContain('U+20BB7')
  } finally {
    rmSync(outputDir, { recursive: true, force: true })
  }
})

it('subsets a TTF from a text file through the package bin', () => {
  const outputDir = mkdtempSync(
    resolve(tmpdir(), 'fontmin-rs-bin-subset-file-'),
  )
  const textFile = resolve(outputDir, 'chars.txt')
  const output = resolve(outputDir, 'roboto-subset.ttf')

  writeFileSync(textFile, 'Hello')

  try {
    execFileSync(process.execPath, [
      bin,
      'subset',
      fixture,
      '-o',
      output,
      '--text-file',
      textFile,
    ])

    expect(readFileSync(output).byteLength).toBeLessThan(
      readFileSync(fixture).byteLength,
    )
  } finally {
    rmSync(outputDir, { recursive: true, force: true })
  }
})

it('reports subset metrics from the package bin bench command', () => {
  const workDir = mkdtempSync(resolve(tmpdir(), 'fontmin-rs-bin-bench-'))
  const textFile = resolve(workDir, 'chars.txt')

  writeFileSync(textFile, 'Hello')

  try {
    const stdout = execFileSync(
      process.execPath,
      [bin, 'bench', fixture, '--text-file', textFile, '--json'],
      { encoding: 'utf8' },
    )
    const report = JSON.parse(stdout) as Record<string, unknown>

    expect(report['operation']).toBe('subset')
    expect(report['inputBytes']).toBe(readFileSync(fixture).byteLength)
    expect(Number(report['outputBytes'])).toBeLessThan(
      readFileSync(fixture).byteLength,
    )
    expect(Number.isInteger(report['elapsedMs'])).toBe(true)
  } finally {
    rmSync(workDir, { recursive: true, force: true })
  }
})

it('subsets a TTF from unicodes through the package bin', () => {
  const outputDir = mkdtempSync(
    resolve(tmpdir(), 'fontmin-rs-bin-subset-unicodes-'),
  )
  const output = resolve(outputDir, 'roboto-subset.ttf')

  try {
    execFileSync(process.execPath, [
      bin,
      'subset',
      fixture,
      '-o',
      output,
      '--unicodes',
      '0x48,0x65,0x6c,0x6f',
    ])

    expect(readFileSync(output).byteLength).toBeLessThan(
      readFileSync(fixture).byteLength,
    )
  } finally {
    rmSync(outputDir, { recursive: true, force: true })
  }
})

it('subsets a TTF with the basic text short flag through the package bin', () => {
  const outputDir = mkdtempSync(
    resolve(tmpdir(), 'fontmin-rs-bin-subset-basic-short-'),
  )
  const output = resolve(outputDir, 'roboto-subset.ttf')

  try {
    execFileSync(process.execPath, [bin, 'subset', fixture, '-o', output, '-b'])

    expect(readFileSync(output).byteLength).toBeLessThan(
      readFileSync(fixture).byteLength,
    )
  } finally {
    rmSync(outputDir, { recursive: true, force: true })
  }
})

it('converts a TTF through the package bin', () => {
  const outputDir = mkdtempSync(resolve(tmpdir(), 'fontmin-rs-bin-convert-'))
  const output = resolve(outputDir, 'roboto.woff2')

  try {
    execFileSync(process.execPath, [
      bin,
      'convert',
      fixture,
      '-f',
      'woff2',
      '-o',
      output,
    ])

    const contents = readFileSync(output)
    expect(contents.subarray(0, 4).toString('ascii')).toBe('wOF2')
    expect(contents.byteLength).toBeLessThan(readFileSync(fixture).byteLength)
  } finally {
    rmSync(outputDir, { recursive: true, force: true })
  }
})

it('converts a TTF to EOT through the package bin', () => {
  const outputDir = mkdtempSync(resolve(tmpdir(), 'fontmin-rs-bin-eot-'))
  const output = resolve(outputDir, 'roboto.eot')

  try {
    execFileSync(process.execPath, [
      bin,
      'convert',
      fixture,
      '-f',
      'eot',
      '-o',
      output,
    ])

    const input = readFileSync(fixture)
    const contents = readFileSync(output)

    expect(contents.readUInt32LE(0)).toBe(contents.byteLength)
    expect(contents.readUInt32LE(4)).toBe(input.byteLength)
    expect(contents.subarray(8, 12)).toStrictEqual(
      Buffer.from([0x01, 0x00, 0x02, 0x00]),
    )
    expect(contents.subarray(34, 36)).toStrictEqual(Buffer.from([0x4c, 0x50]))
    expect(
      contents.subarray(contents.byteLength - input.byteLength),
    ).toStrictEqual(input)
  } finally {
    rmSync(outputDir, { recursive: true, force: true })
  }
})

it('converts a TTF to SVG through the package bin', () => {
  const outputDir = mkdtempSync(resolve(tmpdir(), 'fontmin-rs-bin-svg-'))
  const output = resolve(outputDir, 'roboto.svg')

  try {
    execFileSync(process.execPath, [
      bin,
      'convert',
      fixture,
      '-f',
      'svg',
      '-o',
      output,
    ])

    const svg = readFileSync(output, 'utf8')

    expect(svg.startsWith('<svg')).toBe(true)
    expect(svg).toContain('<font ')
    expect(svg).toContain('font-family="Roboto"')
    expect(svg).toContain('unicode="A"')
    expect(svg).toContain('d="M')
  } finally {
    rmSync(outputDir, { recursive: true, force: true })
  }
})

it('decodes a WOFF through the package bin', () => {
  const outputDir = mkdtempSync(resolve(tmpdir(), 'fontmin-rs-bin-woff-'))
  const woff = resolve(outputDir, 'roboto.woff')
  const output = resolve(outputDir, 'roboto.ttf')

  try {
    execFileSync(process.execPath, [
      bin,
      'convert',
      fixture,
      '-f',
      'woff',
      '-o',
      woff,
    ])
    execFileSync(process.execPath, [
      bin,
      'convert',
      woff,
      '-f',
      'ttf',
      '-o',
      output,
    ])

    const contents = readFileSync(output)
    const info = inspect(contents)

    expect(contents.subarray(0, 4)).toStrictEqual(Buffer.from([0, 1, 0, 0]))
    expect(info.format).toBe('ttf')
    expect(info.metadata.fullName).toBe('Roboto Regular')
  } finally {
    rmSync(outputDir, { recursive: true, force: true })
  }
})

it('decodes a WOFF2 through the package bin', () => {
  const outputDir = mkdtempSync(resolve(tmpdir(), 'fontmin-rs-bin-woff2-'))
  const woff2 = resolve(outputDir, 'roboto.woff2')
  const output = resolve(outputDir, 'roboto.ttf')

  try {
    execFileSync(process.execPath, [
      bin,
      'convert',
      fixture,
      '-f',
      'woff2',
      '-o',
      woff2,
    ])
    execFileSync(process.execPath, [
      bin,
      'convert',
      woff2,
      '-f',
      'ttf',
      '-o',
      output,
    ])

    const contents = readFileSync(output)
    const info = inspect(contents)

    expect(contents.subarray(0, 4)).toStrictEqual(Buffer.from([0, 1, 0, 0]))
    expect(info.format).toBe('ttf')
    expect(info.metadata.fullName).toBe('Roboto Regular')
  } finally {
    rmSync(outputDir, { recursive: true, force: true })
  }
})

it('decodes an EOT through the package bin', () => {
  const outputDir = mkdtempSync(resolve(tmpdir(), 'fontmin-rs-bin-eot-decode-'))
  const eot = resolve(outputDir, 'roboto.eot')
  const output = resolve(outputDir, 'roboto.ttf')

  try {
    execFileSync(process.execPath, [
      bin,
      'convert',
      fixture,
      '-f',
      'eot',
      '-o',
      eot,
    ])
    execFileSync(process.execPath, [
      bin,
      'convert',
      eot,
      '-f',
      'ttf',
      '-o',
      output,
    ])

    const contents = readFileSync(output)
    const info = inspect(readFileSync(eot))

    expect(contents.subarray(0, 4)).toStrictEqual(Buffer.from([0, 1, 0, 0]))
    expect(info.format).toBe('eot')
    expect(info.metadata.fullName).toBe('Roboto Regular')
  } finally {
    rmSync(outputDir, { recursive: true, force: true })
  }
})

it('inspects a TTF as JSON through the package bin', () => {
  const output = execFileSync(process.execPath, [
    bin,
    'inspect',
    fixture,
    '--json',
  ])
  const info = JSON.parse(output.toString())

  expect(info.format).toBe('ttf')
  expect(info.metadata.familyName).toBe('Roboto')
  expect(info.metadata.fullName).toBe('Roboto Regular')
})

it('inspects a WOFF as JSON through the package bin', () => {
  const outputDir = mkdtempSync(resolve(tmpdir(), 'fontmin-rs-bin-inspect-'))
  const woff = resolve(outputDir, 'roboto.woff')

  try {
    execFileSync(process.execPath, [
      bin,
      'convert',
      fixture,
      '-f',
      'woff',
      '-o',
      woff,
    ])

    const output = execFileSync(process.execPath, [
      bin,
      'inspect',
      woff,
      '--json',
    ])
    const info = JSON.parse(output.toString())

    expect(info.format).toBe('woff')
    expect(info.size).toBe(readFileSync(woff).byteLength)
    expect(info.metadata.familyName).toBe('Roboto')
    expect(info.metadata.fullName).toBe('Roboto Regular')
  } finally {
    rmSync(outputDir, { recursive: true, force: true })
  }
})
