use super::*;

#[test]
fn init_command_writes_jsonc_config() {
    let tempdir = tempfile::tempdir().unwrap();

    let output = Command::new(env!("CARGO_BIN_EXE_fontmin-rs"))
        .arg("init")
        .current_dir(tempdir.path())
        .output()
        .unwrap();

    assert!(output.status.success());
    assert!(String::from_utf8_lossy(&output.stdout).contains("fontmin.config.jsonc"));

    let config = std::fs::read_to_string(tempdir.path().join("fontmin.config.jsonc")).unwrap();

    assert!(config.contains("Generated by fontmin-rs init"));
    assert!(config.contains("\"input\""));
    assert!(config.contains("\"outputs\""));
    assert!(config.contains("\"woff2\""));
    assert!(config.contains("\"fontDisplay\": \"swap\""));
    assert!(config.contains("\"cache\""));

    let font_dir = tempdir.path().join("fonts");
    std::fs::create_dir(&font_dir).unwrap();
    std::fs::write(font_dir.join("roboto-regular.ttf"), ROBOTO).unwrap();

    let build_output = Command::new(env!("CARGO_BIN_EXE_fontmin-rs"))
        .arg("build")
        .arg("--config")
        .arg("fontmin.config.jsonc")
        .current_dir(tempdir.path())
        .output()
        .unwrap();

    assert!(build_output.status.success());
    assert!(tempdir.path().join("build/roboto-regular.woff2").exists());
    assert!(tempdir.path().join("build/roboto-regular.woff").exists());
    assert!(tempdir.path().join("build/roboto-regular.css").exists());
}

#[test]
fn init_command_refuses_to_overwrite_existing_config() {
    let tempdir = tempfile::tempdir().unwrap();
    let config_path = tempdir.path().join("fontmin.config.jsonc");
    std::fs::write(&config_path, "keep me").unwrap();

    let output = Command::new(env!("CARGO_BIN_EXE_fontmin-rs"))
        .arg("init")
        .current_dir(tempdir.path())
        .output()
        .unwrap();

    assert!(!output.status.success());
    assert_eq!(std::fs::read_to_string(config_path).unwrap(), "keep me");
    assert!(String::from_utf8_lossy(&output.stderr).contains("already exists"));
}

#[test]
fn doctor_command_succeeds() {
    let output = Command::new(env!("CARGO_BIN_EXE_fontmin-rs"))
        .arg("doctor")
        .output()
        .unwrap();

    assert!(output.status.success());
    assert!(String::from_utf8_lossy(&output.stdout).contains("fontmin-rs doctor ok"));
}

#[test]
fn inspect_command_prints_ttf_metadata_as_json() {
    let tempdir = tempfile::tempdir().unwrap();
    let input = tempdir.path().join("roboto.ttf");
    std::fs::write(&input, ROBOTO).unwrap();

    let output = Command::new(env!("CARGO_BIN_EXE_fontmin-rs"))
        .arg("inspect")
        .arg(&input)
        .arg("--json")
        .output()
        .unwrap();

    assert!(output.status.success());

    let info: Value = serde_json::from_slice(&output.stdout).unwrap();
    let metadata = &info["metadata"];

    assert_eq!(info["format"], "ttf");
    assert_eq!(info["size"], ROBOTO.len());
    assert_eq!(metadata["familyName"], "Roboto");
    assert_eq!(metadata["subfamilyName"], "Regular");
    assert_eq!(metadata["fullName"], "Roboto Regular");
    assert_eq!(metadata["postScriptName"], "Roboto-Regular");
    assert_eq!(metadata["glyphCount"], 3387);
    assert_eq!(metadata["unitsPerEm"], 2048);
    assert_eq!(metadata["ascender"], 2146);
    assert_eq!(metadata["descender"], -555);
    assert!(
        metadata["tables"]
            .as_array()
            .unwrap()
            .contains(&Value::String("name".into()))
    );
}

#[test]
fn inspect_command_prints_otf_metadata_as_json() {
    let tempdir = tempfile::tempdir().unwrap();
    let input = tempdir.path().join("roboto.otf");
    let otf = roboto_otf();
    std::fs::write(&input, &otf).unwrap();

    let output = Command::new(env!("CARGO_BIN_EXE_fontmin-rs"))
        .arg("inspect")
        .arg(&input)
        .arg("--json")
        .output()
        .unwrap();

    assert!(output.status.success());

    let info: Value = serde_json::from_slice(&output.stdout).unwrap();
    let metadata = &info["metadata"];

    assert_eq!(info["format"], "otf");
    assert_eq!(info["size"], otf.len());
    assert_eq!(metadata["familyName"], "Roboto");
    assert_eq!(metadata["subfamilyName"], "Regular");
    assert_eq!(metadata["fullName"], "Roboto Regular");
    assert_eq!(metadata["postScriptName"], "Roboto-Regular");
    assert_eq!(metadata["glyphCount"], 3387);
    assert_eq!(metadata["unitsPerEm"], 2048);
    assert_eq!(metadata["ascender"], 2146);
    assert_eq!(metadata["descender"], -555);
    assert!(
        metadata["tables"]
            .as_array()
            .unwrap()
            .contains(&Value::String("name".into()))
    );
}

#[test]
fn inspect_command_prints_woff_metadata_as_json() {
    let tempdir = tempfile::tempdir().unwrap();
    let input = tempdir.path().join("roboto.ttf");
    let woff = tempdir.path().join("roboto.woff");
    std::fs::write(&input, ROBOTO).unwrap();

    let convert_status = Command::new(env!("CARGO_BIN_EXE_fontmin-rs"))
        .arg("convert")
        .arg(&input)
        .arg("-f")
        .arg("woff")
        .arg("-o")
        .arg(&woff)
        .status()
        .unwrap();
    assert!(convert_status.success());

    let output = Command::new(env!("CARGO_BIN_EXE_fontmin-rs"))
        .arg("inspect")
        .arg(&woff)
        .arg("--json")
        .output()
        .unwrap();

    assert!(output.status.success());

    let info: Value = serde_json::from_slice(&output.stdout).unwrap();
    let metadata = &info["metadata"];

    assert_eq!(info["format"], "woff");
    assert_eq!(info["size"], std::fs::metadata(&woff).unwrap().len());
    assert_eq!(metadata["familyName"], "Roboto");
    assert_eq!(metadata["fullName"], "Roboto Regular");
    assert_eq!(metadata["glyphCount"], 3387);
}

#[test]
fn inspect_command_prints_woff2_table_metadata_as_json() {
    let tempdir = tempfile::tempdir().unwrap();
    let input = tempdir.path().join("roboto.ttf");
    let woff2 = tempdir.path().join("roboto.woff2");
    std::fs::write(&input, ROBOTO).unwrap();

    let convert_status = Command::new(env!("CARGO_BIN_EXE_fontmin-rs"))
        .arg("convert")
        .arg(&input)
        .arg("-f")
        .arg("woff2")
        .arg("-o")
        .arg(&woff2)
        .status()
        .unwrap();
    assert!(convert_status.success());

    let output = Command::new(env!("CARGO_BIN_EXE_fontmin-rs"))
        .arg("inspect")
        .arg(&woff2)
        .arg("--json")
        .output()
        .unwrap();

    assert!(output.status.success());

    let info: Value = serde_json::from_slice(&output.stdout).unwrap();
    let metadata = &info["metadata"];

    assert_eq!(info["format"], "woff2");
    assert_eq!(info["size"], std::fs::metadata(&woff2).unwrap().len());
    assert_eq!(metadata["familyName"], "Roboto");
    assert_eq!(metadata["fullName"], "Roboto Regular");
    assert_eq!(metadata["glyphCount"], 3387);
    assert_eq!(metadata["unitsPerEm"], 2048);
    assert!(
        metadata["tables"]
            .as_array()
            .unwrap()
            .contains(&Value::String("name".into()))
    );
}

#[test]
fn inspect_command_prints_eot_metadata_as_json() {
    let tempdir = tempfile::tempdir().unwrap();
    let input = tempdir.path().join("roboto.ttf");
    let eot = tempdir.path().join("roboto.eot");
    std::fs::write(&input, ROBOTO).unwrap();

    let convert_status = Command::new(env!("CARGO_BIN_EXE_fontmin-rs"))
        .arg("convert")
        .arg(&input)
        .arg("-f")
        .arg("eot")
        .arg("-o")
        .arg(&eot)
        .status()
        .unwrap();
    assert!(convert_status.success());

    let output = Command::new(env!("CARGO_BIN_EXE_fontmin-rs"))
        .arg("inspect")
        .arg(&eot)
        .arg("--json")
        .output()
        .unwrap();

    assert!(output.status.success());

    let info: Value = serde_json::from_slice(&output.stdout).unwrap();
    let metadata = &info["metadata"];

    assert_eq!(info["format"], "eot");
    assert_eq!(info["size"], std::fs::metadata(&eot).unwrap().len());
    assert_eq!(metadata["familyName"], "Roboto");
    assert_eq!(metadata["fullName"], "Roboto Regular");
    assert_eq!(metadata["glyphCount"], 3387);
}
