use super::*;

#[test]
fn init_command_writes_jsonc_config() {
    let sandbox = CliSandbox::new();
    let package_dir = sandbox.root().join("node_modules/fontmin-rs");
    std::fs::create_dir_all(&package_dir).unwrap();
    std::fs::write(package_dir.join("configuration_schema.json"), "{}").unwrap();

    let output = sandbox.command().arg("init").output().unwrap();

    assert!(output.status.success());
    assert!(String::from_utf8_lossy(&output.stdout).contains("fontmin.config.jsonc"));

    let config = std::fs::read_to_string(sandbox.root().join("fontmin.config.jsonc")).unwrap();

    assert!(config.contains("Generated by fontmin-rs init"));
    assert!(config.contains(r#""$schema": "./node_modules/fontmin-rs/configuration_schema.json""#));
    assert!(config.contains("\"input\""));
    assert!(config.contains("\"outputs\""));
    assert!(config.contains("\"woff2\""));
    assert!(config.contains("\"fontDisplay\": \"swap\""));
    assert!(config.contains("\"cache\""));

    let font_dir = sandbox.root().join("fonts");
    std::fs::create_dir(&font_dir).unwrap();
    std::fs::write(font_dir.join("roboto-regular.ttf"), ROBOTO).unwrap();

    let build_output = sandbox
        .command()
        .arg("build")
        .arg("--config")
        .arg("fontmin.config.jsonc")
        .output()
        .unwrap();

    assert!(build_output.status.success());
    assert!(sandbox.root().join("build/roboto-regular.woff2").exists());
    assert!(sandbox.root().join("build/roboto-regular.woff").exists());
    assert!(sandbox.root().join("build/roboto-regular.css").exists());
}

#[test]
fn init_command_omits_missing_json_schema() {
    let sandbox = CliSandbox::new();

    let output = sandbox.command().arg("init").output().unwrap();

    assert!(output.status.success());
    let config = std::fs::read_to_string(sandbox.root().join("fontmin.config.jsonc")).unwrap();
    assert!(!config.contains("\"$schema\""));
}

#[test]
fn init_command_refuses_to_overwrite_existing_config() {
    let sandbox = CliSandbox::new();
    let config_path = sandbox.root().join("fontmin.config.jsonc");
    std::fs::write(&config_path, "keep me").unwrap();

    let output = sandbox.command().arg("init").output().unwrap();

    assert!(!output.status.success());
    assert_eq!(std::fs::read_to_string(config_path).unwrap(), "keep me");
    assert!(String::from_utf8_lossy(&output.stderr).contains("already exists"));
}

#[test]
fn doctor_command_succeeds() {
    let output = fontmin_command().arg("doctor").output().unwrap();

    assert!(output.status.success());
    assert!(String::from_utf8_lossy(&output.stdout).contains("fontmin-rs doctor ok"));
}

#[test]
fn inspect_command_prints_ttf_metadata_as_json() {
    let sandbox = CliSandbox::new();
    let input = sandbox.root().join("roboto.ttf");
    sandbox.write_roboto(&input);

    let output = fontmin_command()
        .arg("inspect")
        .arg(&input)
        .arg("--json")
        .output()
        .unwrap();

    assert!(output.status.success());

    let info: Value = serde_json::from_slice(&output.stdout).unwrap();
    let metadata = &info["metadata"];

    assert_eq!(info["format"], "ttf");
    assert_eq!(info["size"], ROBOTO.len());
    assert_eq!(metadata["familyName"], "Roboto");
    assert_eq!(metadata["subfamilyName"], "Regular");
    assert_eq!(metadata["fullName"], "Roboto Regular");
    assert_eq!(metadata["postScriptName"], "Roboto-Regular");
    assert_eq!(metadata["glyphCount"], 3387);
    assert_eq!(metadata["unitsPerEm"], 2048);
    assert_eq!(metadata["ascender"], 2146);
    assert_eq!(metadata["descender"], -555);
    assert!(
        metadata["tables"]
            .as_array()
            .unwrap()
            .contains(&Value::String("name".into()))
    );
}

#[test]
fn inspect_command_prints_otf_metadata_as_json() {
    let sandbox = CliSandbox::new();
    let input = sandbox.root().join("roboto.otf");
    let otf = roboto_otf();
    std::fs::write(&input, &otf).unwrap();

    let output = fontmin_command()
        .arg("inspect")
        .arg(&input)
        .arg("--json")
        .output()
        .unwrap();

    assert!(output.status.success());

    let info: Value = serde_json::from_slice(&output.stdout).unwrap();
    let metadata = &info["metadata"];

    assert_eq!(info["format"], "otf");
    assert_eq!(info["size"], otf.len());
    assert_eq!(metadata["familyName"], "Roboto");
    assert_eq!(metadata["subfamilyName"], "Regular");
    assert_eq!(metadata["fullName"], "Roboto Regular");
    assert_eq!(metadata["postScriptName"], "Roboto-Regular");
    assert_eq!(metadata["glyphCount"], 3387);
    assert_eq!(metadata["unitsPerEm"], 2048);
    assert_eq!(metadata["ascender"], 2146);
    assert_eq!(metadata["descender"], -555);
    assert!(
        metadata["tables"]
            .as_array()
            .unwrap()
            .contains(&Value::String("name".into()))
    );
}

#[test]
fn inspect_command_prints_woff_metadata_as_json() {
    let sandbox = CliSandbox::new();
    let input = sandbox.root().join("roboto.ttf");
    let woff = sandbox.root().join("roboto.woff");
    sandbox.write_roboto(&input);

    let convert_status = fontmin_command()
        .arg("convert")
        .arg(&input)
        .arg("-f")
        .arg("woff")
        .arg("-o")
        .arg(&woff)
        .status()
        .unwrap();
    assert!(convert_status.success());

    let output = fontmin_command()
        .arg("inspect")
        .arg(&woff)
        .arg("--json")
        .output()
        .unwrap();

    assert!(output.status.success());

    let info: Value = serde_json::from_slice(&output.stdout).unwrap();
    let metadata = &info["metadata"];

    assert_eq!(info["format"], "woff");
    assert_eq!(info["size"], std::fs::metadata(&woff).unwrap().len());
    assert_eq!(metadata["familyName"], "Roboto");
    assert_eq!(metadata["fullName"], "Roboto Regular");
    assert_eq!(metadata["glyphCount"], 3387);
}

#[test]
fn inspect_command_prints_woff2_table_metadata_as_json() {
    let sandbox = CliSandbox::new();
    let input = sandbox.root().join("roboto.ttf");
    let woff2 = sandbox.root().join("roboto.woff2");
    sandbox.write_roboto(&input);

    let convert_status = fontmin_command()
        .arg("convert")
        .arg(&input)
        .arg("-f")
        .arg("woff2")
        .arg("-o")
        .arg(&woff2)
        .status()
        .unwrap();
    assert!(convert_status.success());

    let output = fontmin_command()
        .arg("inspect")
        .arg(&woff2)
        .arg("--json")
        .output()
        .unwrap();

    assert!(output.status.success());

    let info: Value = serde_json::from_slice(&output.stdout).unwrap();
    let metadata = &info["metadata"];

    assert_eq!(info["format"], "woff2");
    assert_eq!(info["size"], std::fs::metadata(&woff2).unwrap().len());
    assert_eq!(metadata["familyName"], "Roboto");
    assert_eq!(metadata["fullName"], "Roboto Regular");
    assert_eq!(metadata["glyphCount"], 3387);
    assert_eq!(metadata["unitsPerEm"], 2048);
    assert!(
        metadata["tables"]
            .as_array()
            .unwrap()
            .contains(&Value::String("name".into()))
    );
}

#[test]
fn inspect_command_prints_eot_metadata_as_json() {
    let sandbox = CliSandbox::new();
    let input = sandbox.root().join("roboto.ttf");
    let eot = sandbox.root().join("roboto.eot");
    sandbox.write_roboto(&input);

    let convert_status = fontmin_command()
        .arg("convert")
        .arg(&input)
        .arg("-f")
        .arg("eot")
        .arg("-o")
        .arg(&eot)
        .status()
        .unwrap();
    assert!(convert_status.success());

    let output = fontmin_command()
        .arg("inspect")
        .arg(&eot)
        .arg("--json")
        .output()
        .unwrap();

    assert!(output.status.success());

    let info: Value = serde_json::from_slice(&output.stdout).unwrap();
    let metadata = &info["metadata"];

    assert_eq!(info["format"], "eot");
    assert_eq!(info["size"], std::fs::metadata(&eot).unwrap().len());
    assert_eq!(metadata["familyName"], "Roboto");
    assert_eq!(metadata["fullName"], "Roboto Regular");
    assert_eq!(metadata["glyphCount"], 3387);
}
