import { createRequire } from 'node:module'

const require = createRequire(import.meta.url)
const binding = require('./bindings.js')

export const {
  analyzeCoverage,
  analyzeCoverageAsync,
  createTtfSubsetPlan,
  eotToTtf,
  eotToTtfAsync,
  extractCollectionFace,
  generateFontFaceCss,
  generateFontFaceCssAsync,
  inspectCollection,
  inspectCapabilities,
  inspectFont,
  inspectFontAsync,
  instantiateFont,
  instantiateFontAsync,
  otfToTtf,
  otfToTtfAsync,
  reduceVariationSpace,
  reduceVariationSpaceAsync,
  subsetTtf,
  subsetTtfAsync,
  subsetTtfWithPlan,
  subsetTtfWithReport,
  svgFontToTtf,
  svgFontToTtfAsync,
  svgsToTtf,
  svgsToTtfAsync,
  ttfToEot,
  ttfToEotAsync,
  ttfToSvg,
  ttfToSvgAsync,
  ttfToWoff,
  ttfToWoffAsync,
  ttfToWoff2,
  ttfToWoff2Async,
  validateWoff2,
  woff2ToTtf,
  woff2ToTtfAsync,
  woffToTtf,
  woffToTtfAsync,
} = binding
