/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function eotToTtf(input: Buffer): Buffer

export declare function generateFontFaceCss(
  sources: Array<JsCssFontSource>,
  options?: JsCssOptions | undefined | null,
): string

export declare function inspectFont(input: Buffer): JsFontInfo

export interface JsCssFontSource {
  fileName: string
  format: string
  contents?: Buffer
  glyphs?: Array<JsCssGlyph>
  unicodeRanges?: Array<string>
}

export interface JsCssGlyph {
  name?: string
  unicode: number
}

export interface JsCssOptions {
  fontFamily?: string
  fontPath?: string
  base64?: boolean
  glyph?: boolean
  iconPrefix?: string
  asFileName?: boolean
  local?: boolean
  fontDisplay?: string
  target?: string
  unicodeRanges?: Array<string>
}

export interface JsEotOptions {
  version?: number
}

export interface JsFontInfo {
  format: string
  size: number
  metadata: JsFontMetadata
}

export interface JsFontMetadata {
  familyName?: string
  subfamilyName?: string
  fullName?: string
  postScriptName?: string
  glyphCount: number
  unitsPerEm: number
  ascender: number
  descender: number
  tables: Array<string>
}

export interface JsOtf2TtfOptions {
  preserveHinting?: boolean
  variationCoordinates?: Record<string, number>
}

export interface JsSubsetOptions {
  text?: string
  unicodes?: Array<number>
  unicodeRanges?: Array<string>
  basicText?: boolean
  preserveHinting?: boolean
  trim?: boolean
  keepNotdef?: boolean
  keepLayout?: string
}

export interface JsSvg2TtfOptions {
  normalize?: boolean
  hinting?: boolean
}

export interface JsSvgIcon {
  name: string
  contents: string
  unicode?: number
}

export interface JsSvgOptions {
  fontFamily?: string
}

export interface JsSvgs2TtfOptions {
  fontName?: string
  startUnicode?: number
  ascent?: number
  descent?: number
  normalize?: boolean
}

export interface JsWoff2Options {
  quality?: number
}

export interface JsWoffOptions {
  deflate?: boolean
  compressionLevel?: number
  metadata?: string
  privateData?: Buffer
}

export declare function otfToTtf(
  input: Buffer,
  options?: JsOtf2TtfOptions | undefined | null,
): Buffer

export declare function subsetTtf(
  input: Buffer,
  options?: JsSubsetOptions | undefined | null,
): Buffer

export declare function svgFontToTtf(
  input: string,
  options?: JsSvg2TtfOptions | undefined | null,
): Buffer

export declare function svgsToTtf(
  inputs: Array<JsSvgIcon>,
  options?: JsSvgs2TtfOptions | undefined | null,
): Buffer

export declare function ttfToEot(
  input: Buffer,
  options?: JsEotOptions | undefined | null,
): Buffer

export declare function ttfToSvg(
  input: Buffer,
  options?: JsSvgOptions | undefined | null,
): string

export declare function ttfToWoff(
  input: Buffer,
  options?: JsWoffOptions | undefined | null,
): Buffer

export declare function ttfToWoff2(
  input: Buffer,
  options?: JsWoff2Options | undefined | null,
): Buffer

export declare function validateWoff2(input: Buffer): void

export declare function woff2ToTtf(input: Buffer): Buffer

export declare function woffToTtf(input: Buffer): Buffer
