/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function analyzeCoverage(
  input: Buffer,
  options?: JsCoverageOptions | undefined | null,
): JsCoverageReport

export declare function createTtfSubsetPlan(
  input: Buffer,
  options?: JsSubsetOptions | undefined | null,
): JsSubsetPlan

export declare function eotToTtf(input: Buffer): Buffer

export declare function extractCollectionFace(
  input: Buffer,
  faceIndex: number,
): Buffer

export declare function generateFontFaceCss(
  sources: Array<JsCssFontSource>,
  options?: JsCssOptions | undefined | null,
): string

export declare function inspectCapabilities(
  input: Buffer,
): JsFontCapabilityReport

export declare function inspectCollection(input: Buffer): JsFontCollectionInfo

export declare function inspectFont(input: Buffer): JsFontInfo

export declare function instantiateFont(
  input: Buffer,
  options?: JsInstanceOptions | undefined | null,
): Buffer

export interface JsAxisRange {
  min: number
  max: number
  default?: number
}

export interface JsColorFontCapabilityReport {
  isColorFont: boolean
  subsetSupport?: string
  technologies: Array<JsColorFontTechnologyCapability>
}

export interface JsColorFontTechnologyCapability {
  technology: string
  tables: Array<string>
  subsetSupport: string
  version?: number
  detail: string
}

export interface JsCoverageOptions {
  text?: string
  unicodes?: Array<number>
  unicodeRanges?: Array<string>
  basicText?: boolean
}

export interface JsCoverageReport {
  requested: Array<number>
  supported: Array<number>
  missing: Array<number>
  coveragePercent: number
}

export interface JsCssFontSource {
  fileName: string
  format: string
  contents?: Buffer
  glyphs?: Array<JsCssGlyph>
  unicodeRanges?: Array<string>
}

export interface JsCssGlyph {
  name?: string
  unicode: number
}

export interface JsCssOptions {
  fontFamily?: string
  fontPath?: string
  base64?: boolean
  glyph?: boolean
  iconPrefix?: string
  asFileName?: boolean
  local?: boolean
  fontDisplay?: string
  target?: string
  unicodeRanges?: Array<string>
}

export interface JsEotOptions {
  version?: number
}

export interface JsFontCapabilityReport {
  format: string
  color: JsColorFontCapabilityReport
}

export interface JsFontCollectionFaceInfo {
  index: number
  offset: number
  format: string
  size: number
  metadata: JsFontMetadata
  capabilities: JsFontCapabilityReport
}

export interface JsFontCollectionInfo {
  majorVersion: number
  minorVersion: number
  size: number
  faces: Array<JsFontCollectionFaceInfo>
}

export interface JsFontInfo {
  format: string
  size: number
  metadata: JsFontMetadata
}

export interface JsFontMetadata {
  familyName?: string
  subfamilyName?: string
  fullName?: string
  postScriptName?: string
  glyphCount: number
  unitsPerEm: number
  ascender: number
  descender: number
  tables: Array<string>
}

export interface JsGidMapping {
  oldGid: number
  newGid: number
}

export interface JsGlyphNameGidMapping {
  glyphName: string
  oldGid: number
}

export interface JsInstanceOptions {
  variationCoordinates?: Record<string, number>
}

export interface JsOtf2TtfOptions {
  preserveHinting?: boolean
  variationCoordinates?: Record<string, number>
}

export interface JsSubsetOptions {
  text?: string
  unicodes?: Array<number>
  gids?: Array<number>
  glyphNames?: Array<string>
  unicodeRanges?: Array<string>
  basicText?: boolean
  preserveHinting?: boolean
  trim?: boolean
  keepNotdef?: boolean
  retainGids?: boolean
  retainGlyphNames?: boolean
  retainLegacyCmap?: boolean
  retainSymbolCmap?: boolean
  keepLayout?: string
  layoutFeatures?: Array<string>
  layoutScripts?: Array<string>
  layoutLanguages?: Array<string>
  nameIds?: Array<number>
  nameLanguages?: Array<number>
  dropTables?: Array<string>
  passThroughTables?: Array<string>
  missingGlyphs?: string
}

export interface JsSubsetPlan {
  schemaVersion: number
  planSha256: string
  sourceSha256: string
  sourceSize: number
  sourceGlyphs: number
  options: JsSubsetOptions
  coverage: JsCoverageReport
  requestedGids: Array<number>
  supportedGids: Array<number>
  missingGids: Array<number>
  requestedGlyphNames: Array<string>
  supportedGlyphNames: Array<string>
  missingGlyphNames: Array<string>
  glyphNameToOldGid: Array<JsGlyphNameGidMapping>
  unicodeToOldGid: Array<JsUnicodeGidMapping>
  seedGids: Array<number>
}

export interface JsSubsetReport {
  originalSize: number
  subsetSize: number
  glyphsRetained: number
  tablesRetained: Array<string>
  droppedContextSubtables: number
  cffCharstringsVerbatim: boolean
  requestedGids: Array<number>
  supportedGids: Array<number>
  missingGids: Array<number>
  requestedGlyphNames: Array<string>
  supportedGlyphNames: Array<string>
  missingGlyphNames: Array<string>
  glyphNameToOldGid: Array<JsGlyphNameGidMapping>
  oldToNew: Array<JsGidMapping>
  newToOld: Array<number | undefined | null>
  unicodeToOldGid: Array<JsUnicodeGidMapping>
}

export interface JsSubsetResult {
  data: Buffer
  report: JsSubsetReport
}

export interface JsSvg2TtfOptions {
  normalize?: boolean
  hinting?: boolean
}

export interface JsSvgIcon {
  name: string
  contents: string
  unicode?: number
}

export interface JsSvgOptions {
  fontFamily?: string
}

export interface JsSvgs2TtfOptions {
  fontName?: string
  startUnicode?: number
  ascent?: number
  descent?: number
  normalize?: boolean
}

export interface JsUnicodeGidMapping {
  unicode: number
  oldGid: number
}

export interface JsVariationSpaceOptions {
  pins?: Record<string, number>
  ranges?: Record<string, JsAxisRange>
  downgradeCff2?: boolean
}

export interface JsWoff2Options {
  quality?: number
}

export interface JsWoffOptions {
  deflate?: boolean
  compressionLevel?: number
  metadata?: string
  privateData?: Buffer
}

export declare function otfToTtf(
  input: Buffer,
  options?: JsOtf2TtfOptions | undefined | null,
): Buffer

export declare function reduceVariationSpace(
  input: Buffer,
  options?: JsVariationSpaceOptions | undefined | null,
): Buffer

export declare function subsetTtf(
  input: Buffer,
  options?: JsSubsetOptions | undefined | null,
): Buffer

export declare function subsetTtfWithPlan(
  input: Buffer,
  plan: JsSubsetPlan,
): JsSubsetResult

export declare function subsetTtfWithReport(
  input: Buffer,
  options?: JsSubsetOptions | undefined | null,
): JsSubsetResult

export declare function svgFontToTtf(
  input: string,
  options?: JsSvg2TtfOptions | undefined | null,
): Buffer

export declare function svgsToTtf(
  inputs: Array<JsSvgIcon>,
  options?: JsSvgs2TtfOptions | undefined | null,
): Buffer

export declare function ttfToEot(
  input: Buffer,
  options?: JsEotOptions | undefined | null,
): Buffer

export declare function ttfToSvg(
  input: Buffer,
  options?: JsSvgOptions | undefined | null,
): string

export declare function ttfToWoff(
  input: Buffer,
  options?: JsWoffOptions | undefined | null,
): Buffer

export declare function ttfToWoff2(
  input: Buffer,
  options?: JsWoff2Options | undefined | null,
): Buffer

export declare function validateWoff2(input: Buffer): void

export declare function woff2ToTtf(input: Buffer): Buffer

export declare function woffToTtf(input: Buffer): Buffer
