/* Auto-generated by NAPI-RS */
/* eslint-disable */
export interface JsSubsetOptions {
  text?: string
  unicodes?: Array<number>
  basicText?: boolean
  preserveHinting?: boolean
  trim?: boolean
  keepNotdef?: boolean
  keepLayout?: string
}

export declare function subsetTtf(
  input: Buffer,
  options?: JsSubsetOptions | undefined | null,
): Buffer
