import { mkdir, readFile, stat, writeFile } from 'node:fs/promises'
import { basename, dirname, extname, resolve } from 'node:path'
import { findConfig, loadConfig } from './config'
import {
  analyzeCoverage,
  eotToTtf,
  inspect as inspectFont,
  instantiateFont,
  otfToTtf,
  reduceVariationSpace,
  subsetTtf,
  subsetTtfWithReport,
  ttfToEot,
  ttfToSvg,
  ttfToWoff,
  ttfToWoff2,
  woff2ToTtf,
  woffToTtf,
} from './native'
import { optimize } from './optimize'
import { normalizeCacheOptions } from './optimize-storage'
import {
  deliverySlices as deliverySlicesPlugin,
  glyph,
  svgs2ttf,
} from './plugins'
import {
  missingGlyphWarning,
  normalizeDeliverySlices as normalizeRuntimeDeliverySlices,
} from './runtime-neutral/optimize-policy'
import {
  cleanOutputDirectory,
  expandInputPath,
  resolveSubsetTextFile,
} from './workspace-io'

const INIT_CONFIG_FILE = 'fontmin.config.jsonc'
const CONFIG_SCHEMA_PATH = './node_modules/fontmin-rs/configuration_schema.json'
const FONTMIN_VERSION = '1.0.2-rc.1'
let emitWarnings = true
const DEFAULT_INIT_CONFIG = `{
  // Generated by fontmin-rs init.
  "input": ["fonts/*.ttf"],
  "outDir": "build",
  "subset": {
    "text": "Hello",
    "basicText": true
  },
  "outputs": [
    { "format": "woff2" },
    { "format": "woff" },
    { "format": "css" }
  ],
  "css": {
    "fontFamily": "MyFont",
    "fontPath": "./",
    "fontDisplay": "swap"
  },
  "cache": {
    "enabled": true
  }
}
`

export async function runCli(argv = process.argv.slice(2)) {
  const command = argv[0]
  const commandArgs = argv.slice(1)

  try {
    if (
      command === undefined ||
      command === '--help' ||
      command === '-h' ||
      commandArgs.includes('--help') ||
      commandArgs.includes('-h')
    ) {
      usage(process.stdout)
    } else if (command === '--version' || command === '-V') {
      process.stdout.write(`${FONTMIN_VERSION}\n`)
    } else if (command === 'doctor') {
      assertNoUnexpectedArgs(commandArgs, 0)
      process.stdout.write('fontmin-rs doctor ok\n')
    } else if (command === 'subset') {
      await subsetCommand(commandArgs)
    } else if (command === 'coverage') {
      await coverageCommand(commandArgs)
    } else if (command === 'convert') {
      await convertCommand(commandArgs)
    } else if (command === 'instance') {
      await instanceCommand(commandArgs)
    } else if (command === 'build') {
      await buildCommand(commandArgs)
    } else if (command === 'inspect') {
      await inspectCommand(commandArgs)
    } else if (command === 'init') {
      assertNoUnexpectedArgs(commandArgs, 0)
      await initCommand()
    } else if (command === 'bench') {
      await benchCommand(commandArgs)
    } else {
      usage(process.stderr)
      process.exitCode = 1
    }
  } catch (error) {
    process.stderr.write(
      `${error instanceof Error ? error.message : String(error)}\n`,
    )
    process.exitCode = 1
  }
}

async function subsetCommand(args) {
  const output = readOption(args, ['-o', '--output'])
  const reportPath = readOption(args, ['--report'])
  const subsetOptions = await subsetOptionsFromArgs(args, {
    allowGlyphSelectors: true,
  })
  const basicText = readFlag(args, ['-b', '--basic-text'])
  assertNoUnexpectedArgs(args)
  const [input] = args

  requireValue(input, 'subset requires an input font')
  requireValue(output, 'subset requires -o, --output')
  if (
    subsetOptions.text === undefined &&
    subsetOptions.unicodes.length === 0 &&
    subsetOptions.gids.length === 0 &&
    subsetOptions.glyphNames.length === 0 &&
    !basicText
  ) {
    throw new Error(
      'subset requires --text, --text-file, --unicodes, --gids, --glyph-names, or --basic-text',
    )
  }

  const contents = await readFile(input)
  const options = {
    basicText,
    gids: subsetOptions.gids,
    glyphNames: subsetOptions.glyphNames,
    layoutFeatures: subsetOptions.layoutFeatures,
    layoutScripts: subsetOptions.layoutScripts,
    layoutLanguages: subsetOptions.layoutLanguages,
    nameIds: subsetOptions.nameIds,
    nameLanguages: subsetOptions.nameLanguages,
    dropTables: subsetOptions.dropTables,
    passThroughTables: subsetOptions.passThroughTables,
    missingGlyphs: subsetOptions.missingGlyphs,
    retainGids: subsetOptions.retainGids,
    retainGlyphNames: subsetOptions.retainGlyphNames,
    retainLegacyCmap: subsetOptions.retainLegacyCmap,
    retainSymbolCmap: subsetOptions.retainSymbolCmap,
    text: subsetOptions.text,
    unicodes: subsetOptions.unicodes,
  }

  if (reportPath !== undefined) {
    if (resolve(reportPath) === resolve(output)) {
      throw new Error(
        'subset report path must differ from the font output path',
      )
    }
    warnForMissingUnicode(contents, options)
    const result = subsetTtfWithReport(contents, optionsAfterCoverage(options))

    await writeOutput(output, result.data)
    await writeOutput(
      reportPath,
      `${JSON.stringify(result.report, undefined, 2)}\n`,
    )
    return
  }

  await writeOutput(output, subsetWithCoverage(contents, options))
}

async function coverageCommand(args) {
  const json = readFlag(args, ['--json'])
  const basicText = readFlag(args, ['-b', '--basic-text'])
  const options = await subsetOptionsFromArgs(args)
  assertNoUnexpectedArgs(args)
  const [input] = args

  requireValue(input, 'coverage requires an input font')
  if (
    options.text === undefined &&
    options.unicodes.length === 0 &&
    !basicText
  ) {
    throw new Error(
      'coverage requires --text, --text-file, --unicodes, or --basic-text',
    )
  }

  const report = analyzeCoverage(await readFile(input), {
    basicText,
    text: options.text,
    unicodes: options.unicodes,
  })

  if (json) {
    process.stdout.write(`${JSON.stringify(report, undefined, 2)}\n`)
    return
  }

  process.stdout.write(
    `coverage: ${report.coveragePercent.toFixed(2)}% (${report.supported.length}/${report.requested.length})\nrequested: ${report.requested.length}\nsupported: ${report.supported.length}\nmissing: ${report.missing.length}\n`,
  )
  const warning = missingGlyphWarning(report)
  if (warning !== undefined) {
    process.stdout.write(`${warning}\n`)
  }
}

async function convertCommand(args) {
  const output = readOption(args, ['-o', '--output'])
  const format = readOption(args, ['-f', '--format'])
  const variationCoordinates = parseVariations(
    readOptions(args, ['--variation']),
  )
  assertNoUnexpectedArgs(args)
  const [input] = args

  requireValue(input, 'convert requires an input font')
  requireValue(output, 'convert requires -o, --output')
  requireValue(format, 'convert requires -f, --format')

  const contents = await readFile(input)
  const converted = convertFont(contents, format, { variationCoordinates })

  await writeOutput(output, converted)
}

async function instanceCommand(args) {
  const output = readOption(args, ['-o', '--output'])
  const variationValues = readOptions(args, ['--variation'])
  const variationRangeValues = readOptions(args, ['--variation-range'])
  const keepVariable = readFlag(args, ['--keep-variable'])
  const downgradeCff2 = readFlag(args, ['--downgrade-cff2'])
  const variationCoordinates = parseVariations(variationValues)
  const variationRanges = parseVariationRanges(variationRangeValues)
  assertNoUnexpectedArgs(args)
  const [input] = args

  requireValue(input, 'instance requires an input font')
  requireValue(output, 'instance requires -o, --output')

  const contents = await readFile(input)
  const preserveDesignSpace =
    keepVariable || variationRangeValues.length > 0 || downgradeCff2
  let instanced

  if (preserveDesignSpace) {
    for (const tag of Object.keys(variationRanges)) {
      if (Object.hasOwn(variationCoordinates, tag)) {
        throw new Error(
          `variation axis \`${tag}\` cannot be both pinned and ranged`,
        )
      }
    }
    instanced = reduceVariationSpace(contents, {
      axes: { ...variationCoordinates, ...variationRanges },
      downgradeCff2,
    })
  } else {
    instanced = instantiateFont(contents, { variationCoordinates })
  }

  await writeOutput(output, instanced)
}

async function benchCommand(args) {
  const json = readFlag(args, ['--json'])
  const basicText = readFlag(args, ['-b', '--basic-text'])
  const subsetOptions = await subsetOptionsFromArgs(args)
  assertNoUnexpectedArgs(args)
  const [input] = args

  requireValue(input, 'bench requires an input font')
  if (
    subsetOptions.text === undefined &&
    subsetOptions.unicodes.length === 0 &&
    !basicText
  ) {
    throw new Error(
      'bench requires --text, --text-file, --unicodes, or --basic-text',
    )
  }

  const contents = await readFile(input)
  const startedAt = process.hrtime.bigint()
  const subset = subsetWithCoverage(contents, {
    basicText,
    missingGlyphs: subsetOptions.missingGlyphs,
    text: subsetOptions.text,
    unicodes: subsetOptions.unicodes,
  })
  const elapsedMs = Math.round(
    Number(process.hrtime.bigint() - startedAt) / 1_000_000,
  )
  const report = {
    elapsedMs,
    inputBytes: contents.byteLength,
    operation: 'subset',
    outputBytes: subset.byteLength,
  }

  if (json) {
    process.stdout.write(`${JSON.stringify(report)}\n`)
  } else {
    process.stdout.write(
      `fontmin-rs bench subset completed in ${elapsedMs} ms\ninput: ${report.inputBytes} bytes\noutput: ${report.outputBytes} bytes\n`,
    )
  }
}

async function buildCommand(args) {
  const showTime = readFlag(args, ['-T', '--show-time'])
  const silent = readFlag(args, ['--silent'])
  const startedAt = showTime && !silent ? process.hrtime.bigint() : undefined

  emitWarnings = !silent
  try {
    await runBuildCommand(args)
    reportShowTime(startedAt)
  } finally {
    emitWarnings = true
  }
}

async function runBuildCommand(args) {
  const configPath = readOption(args, ['-c', '--config'])
  const cache = readFlag(args, ['--cache'])
  const noCache = readFlag(args, ['--no-cache'])
  const noOriginal = readFlag(args, ['--no-original'])
  readFlag(args, ['-d', '--deflate-woff'])
  const cssGlyph = readFlag(args, ['--css-glyph'])
  const cssUnicodeRanges = parseUnicodeRanges(
    readOptions(args, ['--css-unicode-range']),
  )
  const deliverySlices = parseDeliverySlices(
    readOptions(args, ['--delivery-slice']),
  )
  const autoDelivery = parseAutoDeliveryOptions({
    enabled: readFlag(args, ['--auto-delivery']),
    frequencyText: readOption(args, ['--delivery-frequency-text']),
    languages: readOption(args, ['--delivery-languages']),
    maxSlices: readOption(args, ['--delivery-max-slices']),
    measureFormat: readOption(args, ['--delivery-measure-format']),
    targetBytes: readOption(args, ['--delivery-target-bytes']),
    tolerance: readOption(args, ['--delivery-tolerance']),
  })
  const outDir = readOption(args, ['-o', '--out-dir'])
  const formats = readOption(args, ['--formats'])
  const preset = readOption(args, ['--preset'])
  const basicText = readFlag(args, ['-b', '--basic-text'])
  const fontFamily = readOption(args, ['--font-family'])
  const fontPath = readOption(args, ['--font-path'])
  const variationCoordinates = parseVariations(
    readOptions(args, ['--variation']),
  )
  const subsetOptions = await subsetOptionsFromArgs(args, {
    allowGlyphSelectors: true,
  })
  assertNoUnknownOptions(args)

  if (cache && noCache) {
    throw new Error('build accepts only one of --cache or --no-cache')
  }
  if (autoDelivery !== undefined && deliverySlices.length > 0) {
    throw new Error(
      'build accepts only one of --auto-delivery options or --delivery-slice',
    )
  }

  const cacheOverride = cacheOverrideFromFlags(cache, noCache)

  if (configPath !== undefined) {
    if (isIconfontPreset(preset)) {
      await buildIconfontConfigCommand(configPath, {
        fontFamily,
        fontPath,
        formats,
        inputs: [...args],
        cacheOverride,
        autoDelivery,
        cssUnicodeRanges,
        deliverySlices,
        outDir,
        variationCoordinates,
      })
      return
    }

    await buildConfigCommand(configPath, {
      basicText,
      autoDelivery,
      cacheOverride,
      cssGlyph,
      cssUnicodeRanges,
      deliverySlices,
      fontFamily,
      fontPath,
      formats,
      inputs: [...args],
      noOriginal,
      outDir,
      preset,
      subsetOptions,
      variationCoordinates,
    })
    return
  }

  if (args.length === 0) {
    const foundConfigPath = await findConfig()

    if (isIconfontPreset(preset)) {
      await buildIconfontConfigCommand(foundConfigPath, {
        fontFamily,
        fontPath,
        formats,
        cacheOverride,
        autoDelivery,
        cssUnicodeRanges,
        deliverySlices,
        outDir,
        variationCoordinates,
      })
      return
    }

    await buildConfigCommand(foundConfigPath, {
      basicText,
      autoDelivery,
      cacheOverride,
      cssGlyph,
      cssUnicodeRanges,
      deliverySlices,
      fontFamily,
      fontPath,
      formats,
      noOriginal,
      outDir,
      preset,
      subsetOptions,
      variationCoordinates,
    })
    return
  }

  const inputPatterns = [...args]
  const [input] = inputPatterns

  requireValue(input, 'build requires an input font')
  requireValue(outDir, 'build requires -o, --out-dir')

  if (isIconfontPreset(preset)) {
    if (formats !== undefined) {
      throw new Error('build accepts only one of --formats or --preset')
    }
    if (deliverySlices.length > 0) {
      throw new Error('iconfont preset does not support delivery slices')
    }
    if (autoDelivery !== undefined) {
      throw new Error(
        'iconfont preset does not support automatic delivery slices',
      )
    }

    const inputs = await expandInputPaths(inputPatterns, process.cwd())
    const cacheOptions = normalizeCacheOptions(
      undefined,
      process.cwd(),
      cacheOverride,
    )

    await buildIconfontCommand(
      inputs,
      outDir,
      fontFamily,
      fontPath ?? './',
      [],
      {},
      cacheOptions,
      cssUnicodeRanges,
    )
    return
  }

  const inputs = await expandInputPaths(inputPatterns, process.cwd())
  const outputFormats = filterOriginalOutput(
    outputFormatsFromArgs(formats, preset),
    noOriginal,
  )
  const cacheOptions = normalizeCacheOptions(
    undefined,
    process.cwd(),
    cacheOverride,
  )
  if (outputFormats.length === 0) {
    throw new Error('build requires at least one non-original output format')
  }
  assertCssHasFontOutput(outputFormats)

  await mkdir(outDir, { recursive: true })

  for (const input of inputs) {
    await buildDirectInput(input, outDir, {
      basicText,
      autoDelivery,
      cacheOptions,
      cssGlyph,
      cssUnicodeRanges,
      deliverySlices,
      fontFamily,
      fontPath,
      outputFormats,
      subsetOptions,
      variationCoordinates,
    })
  }
}

async function buildDirectInput(
  input,
  outDir,
  {
    basicText,
    autoDelivery,
    cacheOptions,
    cssGlyph,
    cssUnicodeRanges,
    deliverySlices,
    fontFamily,
    fontPath,
    outputFormats,
    subsetOptions,
    variationCoordinates,
  },
) {
  const baseName = basename(input, extname(input))
  const shouldSubset = !(
    subsetOptions.text === undefined &&
    subsetOptions.unicodes.length === 0 &&
    subsetOptions.gids.length === 0 &&
    subsetOptions.glyphNames.length === 0 &&
    subsetOptions.layoutFeatures.length === 0 &&
    subsetOptions.layoutScripts.length === 0 &&
    subsetOptions.layoutLanguages.length === 0 &&
    subsetOptions.nameIds.length === 0 &&
    subsetOptions.nameLanguages.length === 0 &&
    subsetOptions.dropTables.length === 0 &&
    subsetOptions.passThroughTables.length === 0 &&
    !basicText
  )
  const plugins = [normalizeToTtfPlugin(variationCoordinates)]

  if (shouldSubset) {
    plugins.push(
      glyph({
        basicText,
        gids: subsetOptions.gids,
        glyphNames: subsetOptions.glyphNames,
        layoutFeatures: subsetOptions.layoutFeatures,
        layoutScripts: subsetOptions.layoutScripts,
        layoutLanguages: subsetOptions.layoutLanguages,
        nameIds: subsetOptions.nameIds,
        nameLanguages: subsetOptions.nameLanguages,
        dropTables: subsetOptions.dropTables,
        passThroughTables: subsetOptions.passThroughTables,
        missingGlyphs: subsetOptions.missingGlyphs,
        retainGids: subsetOptions.retainGids,
        retainGlyphNames: subsetOptions.retainGlyphNames,
        retainLegacyCmap: subsetOptions.retainLegacyCmap,
        retainSymbolCmap: subsetOptions.retainSymbolCmap,
        text: subsetOptions.text,
        unicodes: subsetOptions.unicodes,
      }),
    )
  }
  if (deliverySlices.length > 0) {
    plugins.push(deliverySlicesPlugin(deliverySlices))
  }

  await optimize({
    autoDelivery,
    cache: cacheOptions,
    css: {
      fontFamily: fontFamily ?? baseName,
      fontPath: fontPath ?? './',
      glyph: cssGlyph,
      unicodeRanges: cssUnicodeRanges,
    },
    input: [input],
    outDir,
    outputs: outputFormats,
    plugins,
  })
}

function normalizeToTtfPlugin(variationCoordinates = {}) {
  return {
    name: 'fontmin:normalize-to-ttf',
    native: {
      kind: 'builtin',
      name: 'normalizeToTtf',
      options: { variationCoordinates },
    },
  }
}

function reportShowTime(startedAt) {
  if (startedAt === undefined) {
    return
  }

  const elapsedMs = Number(process.hrtime.bigint() - startedAt) / 1_000_000

  process.stdout.write(
    `fontmin-rs build completed in ${Math.round(elapsedMs)} ms\n`,
  )
}

async function buildIconfontCommand(
  inputs,
  outDir,
  fontFamily,
  fontPath,
  outputs = [],
  css = {},
  cacheOptions = normalizeCacheOptions(undefined, process.cwd()),
  cssUnicodeRanges = css.unicodeRanges ?? [],
) {
  if (inputs.length === 0) {
    throw new Error('build requires at least one input font')
  }

  const family = fontFamily ?? 'iconfont'
  const fileName = outputFileName(outputs, 'ttf', 'iconfont.ttf')
  const cssFileName = outputFileName(
    outputs,
    'css',
    `${basename(fileName, extname(fileName))}.${css.target ?? 'css'}`,
  )

  await optimize({
    cache: cacheOptions,
    css: {
      ...css,
      asFileName: css.asFileName ?? true,
      fontFamily: family,
      fontPath,
      glyph: true,
      unicodeRanges: cssUnicodeRanges,
    },
    input: inputs,
    outDir,
    outputs: [
      { fileName, format: 'ttf' },
      { fileName: cssFileName, format: 'css' },
    ],
    plugins: [svgs2ttf({ fontName: family })],
  })
}

async function buildConfigCommand(
  configPath,
  {
    autoDelivery,
    basicText,
    cacheOverride,
    cssGlyph,
    cssUnicodeRanges = [],
    deliverySlices = [],
    fontFamily,
    fontPath,
    formats,
    inputs: inputOverrides = [],
    noOriginal,
    outDir: outDirOverride,
    preset,
    subsetOptions,
    variationCoordinates = {},
  } = {},
) {
  const resolvedConfigPath = resolve(configPath)
  const config = await loadConfig(resolvedConfigPath)
  const cwd =
    typeof config.cwd === 'string'
      ? resolve(config.cwd)
      : dirname(resolvedConfigPath)
  const inputs =
    inputOverrides.length > 0 ? inputOverrides : (config.input ?? [])
  const outDir = resolve(cwd, outDirOverride ?? config.outDir ?? 'build')
  const outputFormats = outputFormatsForConfig(config.outputs, {
    formats,
    noOriginal,
    preset,
  })
  const cacheOptions = normalizeCacheOptions(config.cache, cwd, cacheOverride)
  const resolvedVariationCoordinates = {
    ...config.otf?.variationCoordinates,
    ...variationCoordinates,
  }

  if (inputs.length === 0) {
    throw new Error('build config requires at least one input')
  }

  const inputPaths = await expandInputPaths(inputs, cwd)

  if (
    fontFamily !== undefined ||
    fontPath !== undefined ||
    cssGlyph === true ||
    cssUnicodeRanges.length > 0
  ) {
    config.css = {
      ...config.css,
      ...(cssGlyph === true && { glyph: true }),
      ...(cssUnicodeRanges.length > 0 && {
        unicodeRanges: cssUnicodeRanges,
      }),
      ...(fontFamily !== undefined && { fontFamily }),
      ...(fontPath !== undefined && { fontPath }),
    }
  }
  if (deliverySlices.length > 0) {
    config.delivery = { slices: deliverySlices }
  }
  if (autoDelivery !== undefined) {
    config.autoDelivery = autoDelivery
  }
  if (
    config.autoDelivery !== undefined &&
    normalizeDeliverySlices(config.delivery?.slices ?? []).length > 0
  ) {
    throw new Error('build accepts only one of autoDelivery or delivery slices')
  }

  applySubsetOverrides(config, { basicText, subsetOptions })

  if (config.clean === true) {
    await cleanOutputDirectory(cwd, outDir, [resolvedConfigPath, ...inputPaths])
  }

  await mkdir(outDir, { recursive: true })

  for (const inputPath of inputPaths) {
    await buildConfigInput(
      inputPath,
      outDir,
      outputFormats,
      config,
      cwd,
      cacheOptions,
      resolvedVariationCoordinates,
    )
  }
}

async function buildIconfontConfigCommand(
  configPath,
  {
    autoDelivery,
    cacheOverride,
    cssUnicodeRanges = [],
    deliverySlices = [],
    fontFamily,
    fontPath,
    formats,
    inputs: inputOverrides = [],
    outDir: outDirOverride,
  },
) {
  if (formats !== undefined) {
    throw new Error('build accepts only one of --formats or --preset')
  }

  const resolvedConfigPath = resolve(configPath)
  const config = await loadConfig(resolvedConfigPath)
  const cwd =
    typeof config.cwd === 'string'
      ? resolve(config.cwd)
      : dirname(resolvedConfigPath)
  const outDir = resolve(cwd, outDirOverride ?? config.outDir ?? 'build')
  const inputs = await expandConfigInputPaths(
    inputOverrides.length > 0 ? inputOverrides : (config.input ?? []),
    cwd,
  )
  const css = config.css ?? {}
  const cacheOptions = normalizeCacheOptions(config.cache, cwd, cacheOverride)

  if (cssUnicodeRanges.length > 0) {
    css.unicodeRanges = cssUnicodeRanges
  }
  if (deliverySlices.length > 0) {
    config.delivery = { slices: deliverySlices }
  }
  if (autoDelivery !== undefined) {
    config.autoDelivery = autoDelivery
  }
  if (normalizeDeliverySlices(config.delivery?.slices ?? []).length > 0) {
    throw new Error('iconfont preset does not support delivery slices')
  }
  if (config.autoDelivery !== undefined) {
    throw new Error(
      'iconfont preset does not support automatic delivery slices',
    )
  }

  if (config.clean === true) {
    await cleanOutputDirectory(cwd, outDir, [resolvedConfigPath, ...inputs])
  }

  await buildIconfontCommand(
    inputs,
    outDir,
    fontFamily ?? css.fontFamily,
    fontPath ?? css.fontPath ?? './',
    config.outputs ?? [],
    css,
    cacheOptions,
    css.unicodeRanges,
  )
}

function expandConfigInputPaths(inputs, cwd) {
  return expandInputPaths(inputs, cwd)
}

async function expandInputPaths(inputs, cwd) {
  if (inputs.length === 0) {
    throw new Error('build config requires at least one input')
  }

  const paths = []

  for (const input of inputs) {
    if (typeof input !== 'string') {
      throw new TypeError('build config input entries must be file paths')
    }

    paths.push(...(await expandInputPath(input, cwd)))
  }

  return paths
}

function outputFileName(outputs, format, fallback) {
  const output = outputs.find(output => output?.format === format)

  if (typeof output?.fileName === 'string') {
    return output.fileName
  }

  if (typeof output?.ext === 'string') {
    return `${basename(fallback, extname(fallback))}.${normalizeExtension(output.ext)}`
  }

  return fallback
}

function applySubsetOverrides(config, { basicText, subsetOptions } = {}) {
  if (
    subsetOptions === undefined ||
    (subsetOptions.text === undefined &&
      subsetOptions.unicodes.length === 0 &&
      subsetOptions.gids.length === 0 &&
      subsetOptions.glyphNames.length === 0 &&
      subsetOptions.layoutFeatures.length === 0 &&
      subsetOptions.layoutScripts.length === 0 &&
      subsetOptions.layoutLanguages.length === 0 &&
      subsetOptions.nameIds.length === 0 &&
      subsetOptions.nameLanguages.length === 0 &&
      subsetOptions.dropTables.length === 0 &&
      subsetOptions.passThroughTables.length === 0 &&
      basicText !== true &&
      subsetOptions.missingGlyphs === undefined &&
      subsetOptions.retainGids !== true &&
      subsetOptions.retainGlyphNames !== true &&
      subsetOptions.retainLegacyCmap !== true &&
      subsetOptions.retainSymbolCmap !== true)
  ) {
    return
  }

  config.subset = {
    ...config.subset,
    ...(subsetOptions.text !== undefined && { text: subsetOptions.text }),
    ...(subsetOptions.unicodes.length > 0 && {
      unicodes: subsetOptions.unicodes,
    }),
    ...(subsetOptions.gids.length > 0 && { gids: subsetOptions.gids }),
    ...(subsetOptions.glyphNames.length > 0 && {
      glyphNames: subsetOptions.glyphNames,
    }),
    ...(subsetOptions.layoutFeatures.length > 0 && {
      layoutFeatures: subsetOptions.layoutFeatures,
    }),
    ...(subsetOptions.layoutScripts.length > 0 && {
      layoutScripts: subsetOptions.layoutScripts,
    }),
    ...(subsetOptions.layoutLanguages.length > 0 && {
      layoutLanguages: subsetOptions.layoutLanguages,
    }),
    ...(subsetOptions.nameIds.length > 0 && {
      nameIds: subsetOptions.nameIds,
    }),
    ...(subsetOptions.nameLanguages.length > 0 && {
      nameLanguages: subsetOptions.nameLanguages,
    }),
    ...(subsetOptions.dropTables.length > 0 && {
      dropTables: subsetOptions.dropTables,
    }),
    ...(subsetOptions.passThroughTables.length > 0 && {
      passThroughTables: subsetOptions.passThroughTables,
    }),
    ...(subsetOptions.retainGids === true && { retainGids: true }),
    ...(subsetOptions.retainGlyphNames === true && { retainGlyphNames: true }),
    ...(subsetOptions.retainLegacyCmap === true && { retainLegacyCmap: true }),
    ...(subsetOptions.retainSymbolCmap === true && { retainSymbolCmap: true }),
    ...(basicText === true && { basicText }),
    ...(subsetOptions.missingGlyphs !== undefined && {
      missingGlyphs: subsetOptions.missingGlyphs,
    }),
  }
}

async function buildConfigInput(
  input,
  outDir,
  outputFormats,
  config,
  cwd,
  cacheOptions,
  variationCoordinates,
) {
  const subset = await resolveSubsetTextFile(config.subset ?? {}, cwd)
  const baseName = basename(input, extname(input))
  const slices = normalizeDeliverySlices(config.delivery?.slices ?? [])
  const plugins = [normalizeToTtfPlugin(variationCoordinates)]

  if (hasSubsetRequest(subset)) {
    plugins.push(glyph(subset))
  }
  if (slices.length > 0) {
    plugins.push(deliverySlicesPlugin(slices))
  }
  if (Array.isArray(config.plugins)) {
    plugins.push(...config.plugins)
  }

  await optimize({
    autoDelivery: config.autoDelivery,
    cache: cacheOptions,
    css: {
      ...config.css,
      fontFamily: config.css?.fontFamily ?? baseName,
    },
    cwd,
    input: [input],
    outDir,
    outputs: outputConfigsForFormats(config.outputs, outputFormats),
    plugins,
    preserveOriginal: config.preserveOriginal,
    runtime: config.runtime,
  })
}

function hasSubsetRequest(subset) {
  return (
    subset.text !== undefined ||
    (subset.unicodes?.length ?? 0) > 0 ||
    (subset.gids?.length ?? 0) > 0 ||
    (subset.glyphNames?.length ?? 0) > 0 ||
    (subset.layoutFeatures?.length ?? 0) > 0 ||
    (subset.layoutScripts?.length ?? 0) > 0 ||
    (subset.layoutLanguages?.length ?? 0) > 0 ||
    (subset.nameIds?.length ?? 0) > 0 ||
    (subset.nameLanguages?.length ?? 0) > 0 ||
    (subset.dropTables?.length ?? 0) > 0 ||
    (subset.passThroughTables?.length ?? 0) > 0 ||
    (subset.unicodeRanges?.length ?? 0) > 0 ||
    subset.basicText === true
  )
}

function outputConfigsForFormats(outputs, formats) {
  return formats.map(format => {
    const configuredOutput = outputs?.find(output => {
      return (typeof output === 'string' ? output : output.format) === format
    })

    if (typeof configuredOutput === 'object' && configuredOutput !== null) {
      return configuredOutput
    }

    return format
  })
}

function cacheOverrideFromFlags(cache, noCache) {
  if (cache) {
    return true
  }

  if (noCache) {
    return false
  }
}

async function inspectCommand(args) {
  const json = readFlag(args, ['--json'])
  assertNoUnexpectedArgs(args)
  const [input] = args

  requireValue(input, 'inspect requires an input font')

  const contents = await readFile(input)
  const info = inspectFont(contents)

  if (json) {
    process.stdout.write(`${JSON.stringify(info, undefined, 2)}\n`)
  } else {
    process.stdout.write(
      `${input}: ${info.format}, ${info.size} bytes, ${info.metadata.glyphCount} glyphs\n`,
    )
  }
}

async function initCommand() {
  const config = (await hasLocalConfigurationSchema())
    ? DEFAULT_INIT_CONFIG.replace(
        '  "input"',
        `  "$schema": "${CONFIG_SCHEMA_PATH}",\n  "input"`,
      )
    : DEFAULT_INIT_CONFIG

  try {
    await writeFile(INIT_CONFIG_FILE, config, { flag: 'wx' })
  } catch (error) {
    if (hasErrorCode(error, 'EEXIST')) {
      throw new Error(`${INIT_CONFIG_FILE} already exists`, { cause: error })
    }

    throw error
  }

  process.stdout.write(`created ${INIT_CONFIG_FILE}\n`)
}

async function hasLocalConfigurationSchema() {
  try {
    const stats = await stat(CONFIG_SCHEMA_PATH)

    return stats.isFile()
  } catch {
    return false
  }
}

async function subsetOptionsFromArgs(
  args,
  { allowGlyphSelectors = false } = {},
) {
  const subset = await resolveSubsetTextFile(
    {
      text: readOption(args, ['-t', '--text']),
      textFile: readOption(args, ['--text-file']),
      unicodes: parseUnicodes(readOption(args, ['--unicodes'])),
    },
    process.cwd(),
  )

  return {
    ...subset,
    gids: allowGlyphSelectors ? parseGids(readOption(args, ['--gids'])) : [],
    glyphNames: allowGlyphSelectors
      ? parseGlyphNames(readOption(args, ['--glyph-names']))
      : [],
    layoutFeatures: allowGlyphSelectors
      ? parseStringList(
          readOption(args, ['--layout-features']),
          '--layout-features',
        )
      : [],
    layoutScripts: allowGlyphSelectors
      ? parseStringList(
          readOption(args, ['--layout-scripts']),
          '--layout-scripts',
        )
      : [],
    layoutLanguages: allowGlyphSelectors
      ? parseStringList(
          readOption(args, ['--layout-languages']),
          '--layout-languages',
        )
      : [],
    nameIds: allowGlyphSelectors
      ? parseU16List(readOption(args, ['--name-ids']), '--name-ids')
      : [],
    nameLanguages: allowGlyphSelectors
      ? parseU16List(readOption(args, ['--name-languages']), '--name-languages')
      : [],
    dropTables: allowGlyphSelectors
      ? parseTableTags(readOption(args, ['--drop-tables']), '--drop-tables')
      : [],
    passThroughTables: allowGlyphSelectors
      ? parseTableTags(
          readOption(args, ['--pass-through-tables']),
          '--pass-through-tables',
        )
      : [],
    missingGlyphs: parseMissingGlyphPolicy(
      readOption(args, ['--missing-glyphs']),
    ),
    retainGids: allowGlyphSelectors && readFlag(args, ['--retain-gids']),
    retainGlyphNames:
      allowGlyphSelectors && readFlag(args, ['--retain-glyph-names']),
    retainLegacyCmap:
      allowGlyphSelectors && readFlag(args, ['--retain-legacy-cmap']),
    retainSymbolCmap:
      allowGlyphSelectors && readFlag(args, ['--retain-symbol-cmap']),
    unicodes: subset.unicodes ?? [],
  }
}

function subsetWithCoverage(contents, options) {
  warnForMissingUnicode(contents, options)

  return subsetTtf(contents, optionsAfterCoverage(options))
}

function warnForMissingUnicode(contents, options) {
  const policy = options.missingGlyphs ?? 'warn'
  const hasUnicodeSelection =
    options.basicText === true ||
    options.text !== undefined ||
    options.unicodes.length > 0

  if (policy === 'warn' && hasUnicodeSelection) {
    const report = analyzeCoverage(contents, options)
    const warning = missingGlyphWarning(report)

    if (warning !== undefined && emitWarnings) {
      process.stderr.write(`warning: ${warning}\n`)
    }
  }
}

function optionsAfterCoverage(options) {
  const policy = options.missingGlyphs ?? 'warn'

  return {
    ...options,
    missingGlyphs: policy === 'warn' ? 'ignore' : policy,
  }
}

function parseMissingGlyphPolicy(value) {
  if (value === undefined) {
    return
  }

  const policy = value.trim().toLowerCase()

  if (policy === 'ignore' || policy === 'warn' || policy === 'error') {
    return policy
  }

  throw new Error(
    `missing glyph policy must be \`ignore\`, \`warn\`, or \`error\`: ${value}`,
  )
}

function hasErrorCode(error, code) {
  return (
    typeof error === 'object' &&
    error !== null &&
    'code' in error &&
    error.code === code
  )
}

function normalizeExtension(extension) {
  const normalized = extension.replace(/^\.+/u, '')

  if (
    normalized.length === 0 ||
    normalized === '..' ||
    normalized.includes('/') ||
    normalized.includes('\\')
  ) {
    throw new Error(`output extension must be a file extension: ${extension}`)
  }

  return normalized
}

function outputFormatsFromConfig(outputs) {
  if (outputs === undefined) {
    return ['eot', 'woff', 'woff2', 'svg', 'css']
  }

  const formats = outputs.map(output =>
    typeof output === 'string' ? output : output.format,
  )

  return parseFormats(formats.join(','))
}

function outputFormatsForConfig(outputs, { formats, noOriginal, preset }) {
  const outputFormats =
    formats === undefined && preset === undefined
      ? outputFormatsFromConfig(outputs)
      : outputFormatsFromArgs(formats, preset)
  const filtered = filterOriginalOutput(outputFormats, noOriginal)

  if (filtered.length === 0) {
    throw new Error('build requires at least one non-original output format')
  }
  assertCssHasFontOutput(filtered)

  return filtered
}

function assertCssHasFontOutput(formats) {
  if (formats.includes('css') && formats.every(format => format === 'css')) {
    throw new Error('build CSS output requires at least one font format')
  }
}

function outputFormatsFromArgs(formats, preset) {
  if (formats !== undefined && preset !== undefined) {
    throw new Error('build accepts only one of --formats or --preset')
  }

  if (formats !== undefined) {
    return parseFormats(formats)
  }

  if (preset !== undefined) {
    return outputFormatsFromPreset(preset)
  }

  throw new Error('build requires --formats or --preset')
}

function outputFormatsFromPreset(value) {
  const preset = value.trim().toLowerCase()

  if (preset === 'compat') {
    return ['eot', 'svg', 'woff', 'woff2', 'css']
  }

  if (preset === 'modern-web') {
    return ['woff2', 'woff', 'css']
  }

  if (preset === 'iconfont') {
    return ['ttf', 'css']
  }

  throw new Error(`unsupported preset \`${preset}\``)
}

function isIconfontPreset(value) {
  return value?.trim().toLowerCase() === 'iconfont'
}

function filterOriginalOutput(formats, noOriginal) {
  return noOriginal ? formats.filter(format => format !== 'ttf') : formats
}

function parseUnicodeRanges(values) {
  return values.map(value => parseUnicodeRange(value))
}

function formatUnicodeEndpoint(codePoint) {
  return codePoint.toString(16).toUpperCase().padStart(4, '0')
}

function parseUnicodeRange(value) {
  const match =
    /^u\+(?<start>[0-9a-f]{1,6})(?:-(?<end>[0-9a-f]{1,6}))?$/iu.exec(value)

  if (match?.groups === undefined) {
    throw new Error(`invalid Unicode range: ${value}`)
  }

  const start = Number.parseInt(match.groups.start, 16)
  const end = Number.parseInt(match.groups.end ?? match.groups.start, 16)

  if (start > end || end > 0x10_ff_ff || (start <= 0xdf_ff && end >= 0xd8_00)) {
    throw new Error(`invalid Unicode range: ${value}`)
  }

  return start === end
    ? `U+${formatUnicodeEndpoint(start)}`
    : `U+${formatUnicodeEndpoint(start)}-${formatUnicodeEndpoint(end)}`
}

function parseDeliverySlices(values) {
  const slices = []

  for (const value of values) {
    const separator = value.indexOf(':')

    if (separator === -1) {
      throw new Error(`delivery slice must use NAME:RANGE[,RANGE...]: ${value}`)
    }

    const name = value.slice(0, separator)
    const unicodeRanges = value.slice(separator + 1).split(',')
    const existing = slices.find(slice => slice.name === name)

    if (existing === undefined) {
      slices.push({ name, unicodeRanges })
    } else {
      existing.unicodeRanges.push(...unicodeRanges)
    }
  }

  return normalizeDeliverySlices(slices)
}

function parseAutoDeliveryOptions(values) {
  const requested =
    values.enabled ||
    values.frequencyText !== undefined ||
    values.languages !== undefined ||
    values.maxSlices !== undefined ||
    values.measureFormat !== undefined ||
    values.targetBytes !== undefined ||
    values.tolerance !== undefined
  if (!requested) {
    return
  }

  const languages = values.languages?.split(',').map(language => {
    const normalized = language.trim()
    if (
      ![
        'ar',
        'el',
        'en',
        'hi',
        'ja',
        'ko',
        'ru',
        'zh-Hans',
        'zh-Hant',
      ].includes(normalized)
    ) {
      throw new Error(`unsupported delivery language \`${normalized}\``)
    }
    return normalized
  })
  if (languages?.some(language => language.length === 0) === true) {
    throw new Error('--delivery-languages must not be empty')
  }
  if (
    values.measureFormat !== undefined &&
    !['ttf', 'woff', 'woff2'].includes(values.measureFormat)
  ) {
    throw new Error(
      `unsupported --delivery-measure-format \`${values.measureFormat}\`; expected ttf, woff, or woff2`,
    )
  }
  const maxSlices = parseOptionalPositiveInteger(
    values.maxSlices,
    '--delivery-max-slices',
  )
  if (maxSlices !== undefined && maxSlices > 256) {
    throw new Error('--delivery-max-slices must be at most 256')
  }
  const targetBytes = parseOptionalPositiveInteger(
    values.targetBytes,
    '--delivery-target-bytes',
  )
  const tolerance =
    values.tolerance === undefined ? undefined : Number(values.tolerance)
  if (
    tolerance !== undefined &&
    (!Number.isFinite(tolerance) || tolerance < 0 || tolerance >= 1)
  ) {
    throw new Error('--delivery-tolerance must be in [0, 1)')
  }

  return {
    ...(values.frequencyText === undefined
      ? {}
      : { frequencyText: values.frequencyText }),
    ...(languages === undefined ? {} : { languages }),
    ...(maxSlices === undefined ? {} : { maxSlices }),
    ...(values.measureFormat === undefined
      ? {}
      : { measureFormat: values.measureFormat }),
    ...(targetBytes === undefined ? {} : { targetBytes }),
    ...(tolerance === undefined ? {} : { tolerance }),
  }
}

function parseOptionalPositiveInteger(value, option) {
  if (value === undefined) {
    return
  }
  if (!/^[1-9][0-9]*$/u.test(value)) {
    throw new TypeError(`${option} must be a positive integer`)
  }
  const parsed = Number(value)
  if (!Number.isSafeInteger(parsed)) {
    throw new TypeError(`${option} must be a safe positive integer`)
  }

  return parsed
}

function normalizeDeliverySlices(values) {
  return normalizeRuntimeDeliverySlices(values, { allowEmpty: true }).map(
    slice => ({
      name: slice.name,
      unicodeRanges: parseUnicodeRanges(slice.unicodeRanges),
    }),
  )
}

function parseUnicodes(value) {
  if (value === undefined) {
    return []
  }

  const unicodes = value.split(',').map(item => parseUnicodeCodePoint(item))

  if (unicodes.length === 0) {
    throw new Error('expected at least one unicode code point')
  }

  return unicodes
}

function parseUnicodeCodePoint(value) {
  const item = value.trim()

  if (item.length === 0) {
    throw new Error('empty unicode code point in --unicodes')
  }

  let digits = item
  let radix = 10

  if (/^(?:0x|u\+)/iu.test(item)) {
    digits = item.slice(2)
    radix = 16
  }

  const validDigits = radix === 16 ? /^[0-9a-f]+$/iu : /^[0-9]+$/u

  if (!validDigits.test(digits)) {
    throw new Error(`invalid unicode code point \`${item}\``)
  }

  const codePoint = Number.parseInt(digits, radix)

  if (!Number.isInteger(codePoint) || codePoint > 4_294_967_295) {
    throw new Error(`invalid unicode code point \`${item}\``)
  }

  return codePoint
}

function parseGids(value) {
  if (value === undefined) {
    return []
  }

  return value.split(',').map(item => parseGid(item))
}

function parseU16List(value, flag) {
  if (value === undefined) {
    return []
  }

  return value.split(',').map(value => parseU16(value, flag))
}

function parseGlyphNames(value) {
  return parseStringList(value, '--glyph-names', 'glyph name')
}

function parseStringList(value, flag, itemName = 'OpenType tag') {
  if (value === undefined) {
    return []
  }

  return value.split(',').map(item => {
    const parsed = item.trim()

    if (parsed.length === 0) {
      throw new Error(`empty ${itemName} in ${flag}`)
    }

    return parsed
  })
}

function parseTableTags(value, flag) {
  const tags = parseStringList(value, flag, 'OpenType table tag').map(tag =>
    tag.length === 3 ? `${tag} ` : tag,
  )

  for (const tag of tags) {
    if (!/^[ -~]{4}$/u.test(tag)) {
      throw new Error(
        `OpenType table tag \`${tag}\` in ${flag} must be three or four printable ASCII bytes`,
      )
    }
  }

  return tags
}

function parseGid(value) {
  return parseU16(value, '--gids', 'glyph ID')
}

function parseU16(value, flag, itemName = 'numeric ID') {
  const item = value.trim()

  if (item.length === 0) {
    throw new Error(`empty ${itemName} in ${flag}`)
  }

  const hexadecimal = /^0x/iu.test(item)
  const digits = hexadecimal ? item.slice(2) : item
  const validDigits = hexadecimal ? /^[0-9a-f]+$/iu : /^[0-9]+$/u

  if (!validDigits.test(digits)) {
    throw new Error(`invalid ${itemName} \`${item}\` in ${flag}`)
  }

  const parsed = hexadecimal ? Number.parseInt(digits, 16) : Number(digits)

  if (!Number.isInteger(parsed) || parsed > 65_535) {
    throw new Error(`invalid ${itemName} \`${item}\` in ${flag}`)
  }

  return parsed
}

function parseFormats(value) {
  const formats = value
    .split(',')
    .map(format => format.trim().toLowerCase())
    .filter(format => format.length > 0)

  if (formats.length === 0) {
    throw new Error('expected at least one output format')
  }

  for (const format of formats) {
    if (
      format !== 'ttf' &&
      format !== 'woff' &&
      format !== 'woff2' &&
      format !== 'eot' &&
      format !== 'svg' &&
      format !== 'css'
    ) {
      throw new Error(`unsupported output format \`${format}\``)
    }
  }

  return formats
}

function convertFont(contents, format, options = {}) {
  const normalized = format.toLowerCase()

  if (normalized === 'ttf') {
    if (isTtf(contents)) {
      return contents
    }

    if (isWoff(contents)) {
      return woffToTtf(contents)
    }

    if (isWoff2(contents)) {
      return woff2ToTtf(contents)
    }

    if (isEot(contents)) {
      return eotToTtf(contents)
    }

    if (isOtf(contents)) {
      return otfToTtf(contents, {
        variationCoordinates: options.variationCoordinates ?? {},
      })
    }

    throw new Error('unsupported input format for TTF conversion')
  }

  const ttf = convertFont(contents, 'ttf', options)

  if (normalized === 'woff') {
    return ttfToWoff(ttf)
  }

  if (normalized === 'woff2') {
    return ttfToWoff2(ttf)
  }

  if (normalized === 'eot') {
    return ttfToEot(ttf)
  }

  if (normalized === 'svg') {
    return ttfToSvg(ttf)
  }

  throw new Error(`unsupported output format \`${format}\``)
}

function isTtf(contents) {
  return (
    (contents[0] === 0x00 &&
      contents[1] === 0x01 &&
      contents[2] === 0x00 &&
      contents[3] === 0x00) ||
    contents.subarray(0, 4).toString('ascii') === 'true'
  )
}

function isOtf(contents) {
  return contents.subarray(0, 4).toString('ascii') === 'OTTO'
}

function isWoff(contents) {
  return contents.subarray(0, 4).toString('ascii') === 'wOFF'
}

function isWoff2(contents) {
  return contents.subarray(0, 4).toString('ascii') === 'wOF2'
}

function isEot(contents) {
  return (
    contents.byteLength >= 12 &&
    ((contents[8] === 0x01 &&
      contents[9] === 0x00 &&
      contents[10] === 0x02 &&
      contents[11] === 0x00) ||
      (contents[8] === 0x02 &&
        contents[9] === 0x00 &&
        contents[10] === 0x02 &&
        contents[11] === 0x00))
  )
}

function readOption(args, names) {
  const index = args.findIndex(arg => names.includes(arg))

  if (index === -1) {
    return
  }

  const [name] = args.splice(index, 1)
  const [value] = args.splice(index, 1)

  if (value === undefined || value.startsWith('-')) {
    throw new Error(`${name} requires a value`)
  }

  return value
}

function readOptions(args, names) {
  const values = []

  while (args.some(arg => names.includes(arg))) {
    values.push(readOption(args, names))
  }

  return values
}

function readFlag(args, names) {
  const index = args.findIndex(arg => names.includes(arg))

  if (index === -1) {
    return false
  }

  args.splice(index, 1)
  return true
}

function assertNoUnknownOptions(args) {
  const option = args.find(arg => arg.startsWith('-'))

  if (option !== undefined) {
    throw new Error(`unknown option \`${option}\``)
  }
}

function assertNoUnexpectedArgs(args, maximumPositionals = 1) {
  assertNoUnknownOptions(args)

  if (args.length > maximumPositionals) {
    throw new Error(`unexpected argument \`${args[maximumPositionals]}\``)
  }
}

function parseVariations(values) {
  const coordinates = {}

  for (const value of values) {
    const separator = value.indexOf('=')

    if (separator === -1) {
      throw new Error(`invalid variation \`${value}\`; expected TAG=VALUE`)
    }

    const tag = value.slice(0, separator)
    const rawNumber = value.slice(separator + 1)

    if (
      tag.length !== 4 ||
      [...tag].some(character => (character.codePointAt(0) ?? 128) > 127)
    ) {
      throw new Error(
        `invalid variation axis \`${tag}\`; expected four ASCII characters`,
      )
    }
    if (Object.hasOwn(coordinates, tag)) {
      throw new Error(`duplicate variation axis \`${tag}\``)
    }

    const number = Number(rawNumber)

    if (rawNumber.length === 0 || !Number.isFinite(number)) {
      throw new Error(
        `invalid variation value \`${rawNumber}\` for axis \`${tag}\``,
      )
    }

    coordinates[tag] = number
  }

  return coordinates
}

function parseVariationRanges(values) {
  const ranges = {}

  for (const value of values) {
    const separator = value.indexOf('=')

    if (separator === -1) {
      throw new Error(
        `invalid variation range \`${value}\`; expected TAG=MIN:MAX[:DEFAULT]`,
      )
    }
    const tag = value.slice(0, separator)
    const rawRange = value.slice(separator + 1)

    if (
      tag.length !== 4 ||
      [...tag].some(character => (character.codePointAt(0) ?? 128) > 127)
    ) {
      throw new Error(
        `invalid variation axis \`${tag}\`; expected four ASCII characters`,
      )
    }
    if (Object.hasOwn(ranges, tag)) {
      throw new Error(`duplicate variation axis \`${tag}\``)
    }

    const parts = rawRange.split(':')
    if (parts.length < 2 || parts.length > 3) {
      throw new Error(
        `invalid variation range \`${rawRange}\` for axis \`${tag}\`; expected MIN:MAX[:DEFAULT]`,
      )
    }
    const numbers = parts.map(rawNumber => {
      const number = Number(rawNumber)

      if (rawNumber.length === 0 || !Number.isFinite(number)) {
        throw new Error(
          `invalid variation range value \`${rawNumber}\` for axis \`${tag}\``,
        )
      }

      return number
    })
    const [min, max, defaultValue] = numbers

    ranges[tag] = {
      ...(defaultValue === undefined ? {} : { default: defaultValue }),
      max,
      min,
    }
  }

  return ranges
}

function requireValue(value, message) {
  if (value === undefined || value.length === 0) {
    throw new Error(message)
  }
}

async function writeOutput(output, contents) {
  await mkdir(dirname(output), { recursive: true })
  await writeFile(output, contents)
}

function usage(stream) {
  stream.write(`Usage:
  fontmin-rs subset <INPUT> -o|--output <OUTPUT> (-t|--text <TEXT> | --text-file <FILE> | --unicodes <LIST> | --gids <LIST> | --glyph-names <NAMES> | -b|--basic-text) [--retain-gids] [--retain-glyph-names] [--retain-legacy-cmap] [--retain-symbol-cmap] [--layout-features <TAGS>] [--layout-scripts <TAGS>] [--layout-languages <TAGS>] [--name-ids <IDS>] [--name-languages <IDS>] [--drop-tables <TAGS>] [--pass-through-tables <TAGS>] [--missing-glyphs <ignore|warn|error>] [--report <REPORT>]
  fontmin-rs coverage <INPUT> (-t|--text <TEXT> | --text-file <FILE> | --unicodes <LIST> | -b|--basic-text) [--json]
  fontmin-rs convert <INPUT> -f|--format <ttf|woff|woff2|eot|svg> -o|--output <OUTPUT> [--variation <TAG=VALUE>]...
  fontmin-rs instance <INPUT> -o|--output <OUTPUT> [--variation <TAG=VALUE>]... [--variation-range <TAG=MIN:MAX[:DEFAULT]>]... [--keep-variable] [--downgrade-cff2]
  fontmin-rs build <INPUT...> [-c|--config <CONFIG>] [-o|--out-dir <OUT_DIR>] [-t|--text <TEXT>] [--text-file <FILE>] [--unicodes <LIST>] [--gids <LIST>] [--glyph-names <NAMES>] [--retain-gids] [--retain-glyph-names] [--retain-legacy-cmap] [--retain-symbol-cmap] [--layout-features <TAGS>] [--layout-scripts <TAGS>] [--layout-languages <TAGS>] [--name-ids <IDS>] [--name-languages <IDS>] [--drop-tables <TAGS>] [--pass-through-tables <TAGS>] [-b|--basic-text] [--missing-glyphs <ignore|warn|error>] [-d|--deflate-woff] [-T|--show-time] [--silent] [--cache] [--no-cache] [--css-glyph] [--css-unicode-range <RANGE>]... [--delivery-slice <NAME:RANGE[,RANGE...]>]... [--auto-delivery] [--delivery-languages <LANGUAGES>] [--delivery-frequency-text <TEXT>] [--delivery-target-bytes <BYTES>] [--delivery-tolerance <FRACTION>] [--delivery-max-slices <COUNT>] [--delivery-measure-format <ttf|woff|woff2>] [--variation <TAG=VALUE>]... [--formats <FORMATS>] [--preset <compat|modern-web|iconfont>] [--no-original] [--font-family <FONT_FAMILY>] [--font-path <FONT_PATH>]
  fontmin-rs bench <INPUT> [-t|--text <TEXT>] [--text-file <FILE>] [--unicodes <LIST>] [-b|--basic-text] [--json]
  fontmin-rs inspect <INPUT> [--json]
  fontmin-rs init
  fontmin-rs doctor
`)
}
